### ISSUE TITLE
A strict mode where transitive dependencies should be "runtime" by default (not "compile" scope)

### ISSUE THREAD

**Issue by apatrida** [cbeust/kobalt#10]
If you do not explicitly ask for a dependency, you should not compile against it.

So transitive dependencies should go to runtime unless included directly.

Exceptions to the rule:

- a pom that contains no JARs but rather is a list of other POM's brings in the next level as the scope requested instead of runtime
- a pom that contains an empty JAR (no classes, no resources, only pom and typical META-INF contents for a pom that is copied into a JAR) is treated same as above, its next level is treated as the real scoped dependency.

**Comment by cbeust** [comment]
How would that work?

If `a` depends on `b` and my build file declares a dependency on `a`, then `b` must be on the compile class path or it won't compile.

**Comment by apatrida** [comment]
No, you should not use a dependency directly that you do not explicitly ask for.  The transitive dependencies should only be used by library B not by A.   At runtime sure.   But not compile time.   Just because another library uses guava, it shouldn't be Un my compile path unless I say I use guava.  It is accidental use of transitive and those can change at a time you don't expect them to.  So your app should control what you compile against, not some random act of nature.   I hence strict mode.

**Comment by apatrida** [comment]
Some companies and teams have policies against accessing transitives.  Help support that.   It would be the same in   .NET, yiu don't just reach around and compile against random crap
