### ISSUE TITLE
testng reports overwritten by dependent projects in same folder

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#101]
I have a mixed project with java and kotlin parts.  They are in the same folder.  When i run tests with kobalt, the testng output from the java project gets overwritten by the output from the dependent kotlin project.

**Comment by pabl0rg** [comment]
Nevermind!  With the newest Kobalt, this does not happen If i set a separate buildDirectory for each project.

**Comment by cbeust** [comment]
Interesting to see that the same hack that allows this to work on Kobalt allows it to work on IDEA too :-)
