### ISSUE TITLE
upgrading from 0.393 to 0.395 causes new kobalt repo to be created

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#102]
I had 0.393 and ran ./kobaltw --update

Then I saw loads of stuff being downloaded that I already had in my old .kobalt repo.  It seems the changes for the new settings.xml affected the path to the standard repo.

~> find . -name testng-6.9.9.jar
./.kobalt/repository/org/testng/testng/6.9.9/testng-6.9.9.jar
./kobalt/repository/org/testng/testng/6.9.9/testng-6.9.9.jar

**Comment by cbeust** [comment]
Oops, typo. Should be fixed now. And you can delete `~/kobalt/repository`.
