### ISSUE TITLE
if depended-on project changes dependent project's jar should be updated

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#104]
This is related to #103 in a way... 

Currently, I have to manually delete the dependent projects jar file in order for kobalt to generate a new one when only the depended-on project changes.

You can try this using the mixed-example project by checking out revision 98765ba817c60093050397298965b5ffcf481dbb, then assembling, then checking out revision 1bc7ff3d140764ff9ed5ca7d6486e42fb45a5ed9 and calling ./kobaltw assemble again.  The jar is not updated.

Thanks!

**Comment by pabl0rg** [comment]
Hi @cbeust Have you seen this issue?  Effectively it means that on mixed projects incremental compilation is not usable.  (at least as configured in the mentioned mixed example).

Thanks

**Comment by cbeust** [comment]
Practically, it looks like whenever an input checksum changes, I need to see if any project depends on that project and wipe all their input checksums.
