### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property context has not been init

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#110]
When I ./kobaltw compile, I get

ERROR Error: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized

This with a very simple combined java/kotlin project:
https://github.com/pabl0rg/kobalt-mixed-example

**Comment by pabl0rg** [comment]
Tasks seem to be running twice now.

          ╔════════════════════════╗
          ║ Building mixed-example ║
          ╚════════════════════════╝
───── mixed-example:compile
───── mixed-example:compile
───── mixed-example:compileTest
───── mixed-example:compileTest
───── mixed-example:test
───── mixed-example:test
Running tests with classpath size 15
Running tests with classpath size 15
[TestNG] Running:
  Command line suite
[TestNG] Running:
  Command line suite



===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Command line suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

All tests passed
All tests passed
BUILD SUCCESSFUL (1 seconds)

**Comment by cbeust** [comment]
I'm seeing this too, looking.

-- 
Cédric

**Comment by jaredsburrows** [comment]
I am seeing this with Kotlin + Jake Wharton's butterknife.

**Comment by cbeust** [comment]
@jaredsburrows Do you have a project I can build to reproduce this?

**Comment by jagtejsodhi** [comment]
@cbeust working with Jared on the project he was referring to.  The fix was adding 

kapt 'com.jakewharton:butterknife:7.0.1'

and
kapt {
    generateStubs = true
}

**Comment by jaredsburrows** [comment]
@cbeust I was using Kotlin with Jake Wharton's Butterknife and saw this line in an example `build.gradle`: https://github.com/JetBrains/kotlin-examples/blob/master/gradle/android-butterknife/app/build.gradle#L45. I know this is Kotlin + Gradle and not Kobalt. It looks like Kobalt needs to support annotation processing? 

http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/

**Comment by cbeust** [comment]
Kobalt supports annotation processing with `apt` but I haven't tested kapt
yet. I'll take a look.

-- 
Cédric
