### ISSUE TITLE
Error compiling combined java/kotlin 

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#111]
I get these errors when compiling 
https://github.com/pabl0rg/kobalt-mixed-example

───── mixed-example:compile
───── mixed-example:compile
  Compiling 2 files
  Compiling 2 files
src/main/kotlin/com/guatec/KExample.kt:10:58: error: unresolved reference: java
    private val logger = Logger.getLogger(Example::class.java)
                                                         ^
src/main/kotlin/com/guatec/KExample.kt:10:58: error: unresolved reference: java
    private val logger = Logger.getLogger(Example::class.java)
                                                         ^

**Comment by pabl0rg** [comment]
This was due to an error in the Build.kt

Combined projects have to be defined as kotlinProject

**Comment by cbeust** [comment]
Yes, that's why I didn't see that error initially, but while your
workaround works, I still want to figure out why `javaProject` causes this
behavior.

But at least, you're not blocked any more :)


-- 
Cédric
