### ISSUE TITLE
Status code is zero regardless of build failure

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#115]
For some reason, Kobalt exits with a status code of 0 even when a build failed. This can be seen in [this version](https://github.com/sargunster/Klap/tree/c587d4b765082c2b448e26bacefac6d2157de18a) of my project, where I forgot to include the kotlin-reflect jar so the compile fails. 

Travis build showing exit code of zero: https://travis-ci.org/sargunster/Klap/builds/107082976

**Comment by cbeust** [comment]
Can't reproduce so far, here is what I get:

```
───── Klap:clean
───── Klap:compile
  Compiling 6 files
src/main/kotlin/me/sargunvohra/lib/klap/Klap.kt:13:23: error: unresolved reference: jvm
import kotlin.reflect.jvm.jvmName
                      ^
src/main/kotlin/me/sargunvohra/lib/klap/Klap.kt:69:34: error: unresolved reference: primaryConstructor
        val constructor = target.primaryConstructor
                                 ^
                           ^

... plenty more errors

BUILD FAILED: 1
```

**Comment by cbeust** [comment]
I noticed that Travis often doesn't honor the exit code, by the way, but as far as I can tell, Kobalt is exiting with a non zero code.

Maybe file an issue with Travis?

**Comment by sargunster** [comment]
I checked on my local machine as well, and got an exit code of 0 despite
the errors.

**Comment by cbeust** [comment]
Can you paste the full output? Does it say BUILD SUCCESSFUL or FAILED?

**Comment by sargunster** [comment]
I did this in my default shell: 

```
cd ~/Desktop
git clone git@github.com:sargunster/Klap.git
cd Klap
git checkout c587d4b765082c2b448e26bacefac6d2157de18a
./kobaltw compile --log 1; echo "Exit code: $status"
```

Also did the equivalent in Bash for sanity: 

```
cd ~/Desktop
git clone git@github.com:sargunster/Klap.git
cd Klap
git checkout c587d4b765082c2b448e26bacefac6d2157de18a
./kobaltw compile --log 1; echo "Exit code: $#"
```

Both times got `BUILD FAILED: 1` but `Exit code: 0`. Travis also sees the 0 exit code.

Here's the full output:
http://pastebin.com/raw/8PsbqywN
