### ISSUE TITLE
resource file not found in tests

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#126]
Something weird happens when i run ./kobaltw test on this project:
https://github.com/pabl0rg/kobalt-mixed-example

The resource file test-data.txt seems not to be found by the classloader.  In fact, i can't find the file in kobaltBuild.

**Comment by pabl0rg** [comment]
This is the test that fails, btw

`    @Test
    public void testLoadResource() {
        ClassLoader classLoader = getClass().getClassLoader();
        final URL resource = classLoader.getResource("com/guatec/test-data.txt");
        assert (resource != null);
        File f = new File(resource.getFile());
        assert(f.exists());
    }
`

**Comment by cbeust** [comment]
I'm guessing I forget to add `src/test/resources` to the classpath when running the tests, should be easy to fix.

**Comment by pabl0rg** [comment]
Seems to be fixed in .634.  Thanks!

BTW, where was this in the code?  Somewhere in kobalt/plugin/java? I tried to look for the bug, but got lost.

**Comment by cbeust** [comment]
Fundamentally, I had hardcoded `src/main` in a couple of places, so I just had to make this more flexible. The tail end commit of this fix is here:

https://github.com/cbeust/kobalt/commit/9f3f09ea6a312e8c1896d21505574e5cc13c38ff
