### ISSUE TITLE
Product flavors don't work for war project

### ISSUE THREAD

**Issue by nchorniy** [cbeust/kobalt#129]
We are developing a kotlin web project with kobalt. We had some issues with product flavors. 
We were following this example: https://github.com/cbeust/kobalt-examples/tree/master/variants

- The project contains default ​**com.example.Product** class with product name in src/main/kotlin directory and **​application.properties**​ file in src/main/resource directory.
- Versions of those two files are also present for the "pro" flavor.

```
productFlavor("pro") {
}

buildType("debug") {
}

buildType("release") {
}
```
*​*Problem:**​ However when we build the project for the "pro" flavor 

`java -jar kobalt/wrapper/kobalt-wrapper.jar assembleProRelease` 

the target war still contains application.properties and Product class from the default main folder instead of "pro" folder.

This can be verified with the example project: https://bitbucket.org/nchorniy/kobalt-flavor-problem

**Comment by cbeust** [comment]
Should be fixed in the latest. I verified that if I build `./kobaltw assembleProDebug`, the content of `application.properties` is:

```
company-id = Company2
```

but with `./kobaltw assemble`, I get:

```
company-id = Company1
```

Can you update and try again?

**Comment by nchorniy** [comment]
Problem 1: application.properties from "pro" flavor is in the root of built war instead of WEB-INF/classes (there is no use from it there). While application.properties in war:WEB-INF/classes is still taken from the default resources, but not from "pro" flavor.

Problem 2: Product.class in WEB-INF/classes/com/example is also taken from the default folder, not from "pro"

**Comment by cbeust** [comment]
`application.properties` is now going in the right direction, here is what the war looks like now:

```
$ jar tf kobaltBuild/libs/ExampleProject-0.0.1-pro-debug.war
META-INF/MANIFEST.MF
WEB-INF/web.xml
WEB-INF/classes/application.properties
WEB-INF/classes/com/example/BuildConfig$Companion.class
WEB-INF/classes/com/example/BuildConfig.class
WEB-INF/classes/com/example/Product.class
WEB-INF/classes/com/example/WebStarter.class
WEB-INF/lib/kotlin-reflect-1.0.0.jar
WEB-INF/lib/kotlin-runtime-1.0.0.jar
WEB-INF/lib/kotlin-stdlib-1.0.0.jar
```

Can you confirm all three issues are now solved:

- Wrong class picked for flavor
- Wrong properties file picked for the flavor
- `application.properties` in the wrong place

?
