### ISSUE TITLE
Kobalt "profiles" don't work as expected with "sourceDirectoreis"

### ISSUE THREAD

**Issue by andrey-chorniy** [cbeust/kobalt#130]
We were trying to use "--profiles" to organize build-profiles.
in example project two profiles "dev" and "pro" are defined (per http://beust.com/kobalt/documentation/index.html#profiles)

```
  sourceDirectories {
        path("src/main/kotlin")
        if(pro) {
            path("src/pro/kotlin", "src/pro/resources")
        } else if (dev) {
            path("src/dev/kotlin", "src/dev/resources")
        }
    }
```

- The project contains default ​com.example.Product class with product name in src/main/kotlin directory and ​application.properties​ file in src/main/resource directory.
- Versions of those two files are also present under the "src/pro" and "src/dev" directories. In addition to that each "profile" has it's own unique file "pro.properties" and "dev.properties"

war file generated with commands
`java -jar kobalt/wrapper/kobalt-wrapper.jar --profiles dev assemble`
`java -jar kobalt/wrapper/kobalt-wrapper.jar --profiles pro assemble`

**Notes**
Unlike https://github.com/cbeust/kobalt/issues/129 -  "Product class" belong to selected profile.

**Problems**:
1. application.propeties always taken from "main" directory
2. after calling "pro" profile, resulting war file contains files for "dev" (previous build)

Project example: https://bitbucket.org/andrey_chorniy/kobalt-profile-problem/

**Comment by cbeust** [comment]
What you're trying to do should work with product flavors alone, without needing profiles. Can you confirm that?

Next, we can take a look at profiles specifically.
