### ISSUE TITLE
Progress doesn't display properly with a smaller terminal

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#135]
This relates to downloading Kobalt from a wrapper. When the terminal window is small, Kobalt shows download progress on newlines instead of replacing the current line. When the window is larger, it works properly.

```
rm -rf ~/.kobalt/
./kobaltw compile
```

Broken output:
<img width="697" alt="screen shot 2016-02-18 at 10 44 01 pm" src="https://cloud.githubusercontent.com/assets/1320357/13166095/e961ae2a-d691-11e5-889a-11af11db07f5.png">

Working output: 
<img width="1280" alt="screen shot 2016-02-18 at 10 47 04 pm" src="https://cloud.githubusercontent.com/assets/1320357/13166097/f03039e2-d691-11e5-91b0-64cb247619f0.png">

I had a similar issue with another (unrelated) program, and they said it's due to the application not calculating columns correctly. Here's that issue for reference: https://github.com/fishery/spin/issues/1 .

**Comment by cbeust** [comment]
I don't suppose I can close this issue with a curt "Use bigger windows?"  ;-)

**Comment by sargunster** [comment]
The default terminal size on OSX seems to be too small, so probably not :)
