### ISSUE TITLE
Improving beginner's getting started with kobalt

### ISSUE THREAD

**Issue by ccozianu** [cbeust/kobalt#136]
Opening this issue to try to improve beginner's experience based on what I am experiencing as a beginner.

Assuming beginner starts here: http://beust.com/kobalt/getting-started/index.html

0) Not clear what's the target of "getting started" lesson. 
   
   Let's say to create a default java project ready to be built from command line (including publishing to local repository) and to be edited comofortably from IDE (IntelliJ).
 
  This is the point where kobalt should probably disclose that for the time being getting staretd with kobalt means buying into IntelliJ as IDE and Kotlin as language. 

1) Out of the box would not work on windows

because instruction is given about the shell script, this user went to a cygwin bash and got the first error.

instruction should specify for this to run on windows currently, the user can have a cygwin bash but should set the KOBALT_HOME (needed only for bootstrapping the poject, but still needed) to Windows convention nonetheless , example:

    export KOBALT_HOME="c:\\/NPF\\Java\\kobalt\\0.628"  

after which : 
 $KOBALT_HOME/kobaltw --init java

2) Next step: nt clear how to import the project into IntelliJ, I managed to do it, but improving the doc and the tooling will save time and improve the experience in the future

* currently no .iml file. We can instruct the beginner to install the kobalt plugin, got to File -> new ->Project from external sources -> "project from external sources" in the next dialog, disregarding the "import object from external model", 

* At this point the menu "Kobalt/Sync Build File" is still useless, because "--init java" didn't create the src/main/java and src/test /java directories. The user can create them manually, and the run "Kobalt/Sync build file"

3) All that remain is to configure IntelliJ for editing and code assist on build.kbt
... to be continued

Minor, also at the end of first build, user gets "**** Version 0.633 is installed" not clear what is installed where ...

**Comment by cbeust** [comment]
All good points, thanks for the write up!

- About the .iml files: is it possible to check in these files such that they will work for both Windows and MacOS/Linux users? Last time I tried, some paths were incompatible (e.g. Windows paths not working on Mac OS).

- About importing: I just filed https://github.com/cbeust/kobalt/issues/137

**Comment by binkley** [comment]
I also noticed various doc pages use both `kobaltw` (found in PATH) and `./kobaltw` (found in project root).  I'd normalize these, and provide more prominent instructions for self-hosting the build system (e.g., `./gradlew` style).

**Comment by cbeust** [comment]
Only the zip download instructions should use kobaltw, everything else
should use ./kobaltw. Which pages did you see kobaltw used on?
​

-- 
Cédric
