### ISSUE TITLE
Make repositories list overridable/configurable

### ISSUE THREAD

**Issue by AlexCzar** [cbeust/kobalt#141]
It would be really useful if the repositories list was overridable. Some companies have restrictive policies on using repositories, e.g. only Bintray JCenter and not maven central, or only corporate proxy repository.

**Comment by cbeust** [comment]
I'm thinking this list would probably in the `settings.xml` file.

**Comment by cbeust** [comment]
Documentation:  https://github.com/cbeust/kobalt/blob/master/modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Constants.kt#L10
