### ISSUE TITLE
ANTLR support in Kobalt.

### ISSUE THREAD

**Issue by simonorono** [cbeust/kobalt#146]
Just like [Gradle's plugin](https://docs.gradle.org/current/userguide/antlr_plugin.html). Is it viable? Is it possible?

**Comment by cbeust** [comment]
I certainly hope so :-)

I'll take a look.

**Comment by cbeust** [comment]
Done. Here is a first iteration:  https://github.com/cbeust/kobalt-antlr

Let me know if this meets your needs, if you need additional options or functionalities, etc...
