### ISSUE TITLE
Support parent poms

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt#147]
http://repo1.maven.org/maven2/com/squareup/retrofit2/converter-moshi/2.0.0/converter-moshi-2.0.0.pom

defines a parent pom which ultimately resolves to

http://repo1.maven.org/maven2/com/squareup/retrofit2/parent/2.0.0/parent-2.0.0.pom

and defines `moshi.version` to 1.1.0.

Relevant doc: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by sargunster** [comment]
From Slack:
"So the NoSuchMethodError problem with Square library snapshots comes back when I add the JetBrains repository to use Wasabi, so I have to use JitPack.io to build against the version of Wasabi on GitHub instead, but Wasabi still depends on Kotlin snapshots so I have to fork Wasabi to depend on stable Kotlin instead so I can compile while avoiding any repos that could contain a Square snapshot."

**Comment by cbeust** [comment]
Try the latest, it should allow you to use snapshot repos and still resolve these libraries to non-snapshot versions.

I'm leaving this option open because my fix is only a half fix, Kobalt still needs to fully support parent poms.
