### ISSUE TITLE
Support native libraries

### ISSUE THREAD

**Issue by aneophyte** [cbeust/kobalt#153]
I'm experimenting Kobalt with this game library that requires native shared libraries and it should come along with the referenced dependencies. But for some reason upon running the project it can't locate those libraries.

There also was a problem that raised an exception mentioning that it couldn't locate a class which seems to be the one that the dependency that has been included refers to. Adding that dependency manually solved the issue but why was this needed.

The library in question is [this](https://github.com/libgdx/libgdx). The native libraries exist in this [repository](https://github.com/libgdx/libgdx/tree/master/backends/gdx-backend-lwjgl). Also, added [this](http://mvnrepository.com/artifact/org.lwjgl.lwjgl/lwjgl/2.9.3) as a dependency to solve the exception.

[Here](https://github.com/aneophyte/libgdxPlay) is the test project. Please take a look.

**Comment by cbeust** [comment]
Some extra information from @aneophyte:

http://wiki.lwjgl.org/index.php?title=LWJGL_use_in_Maven

**Comment by aneophyte** [comment]
Yes, that shouldn't be required as the "backend" dependency should refer to lwjgl on its own.

**Comment by aneophyte** [comment]
Some progress. Adding native jars and direct dependencies got it working.
https://github.com/aneophyte/libgdxPlay/tree/working_with_jars

**Comment by cbeust** [comment]
That's great, so all you had to do is add a `file()` dependency?


-- 
Cédric

**Comment by aneophyte** [comment]
Yeah, now need to dig a bit deeper with the Gradle one for comparison. The problem wasn't just the native dependency, one of the core library that it referred to ("lwjgl") also had to be added directly.

**Comment by aneophyte** [comment]
Kobalt doesn't seem to fetch all the dependencies. More likely the depdencies of the dependencies.
Gradle log:
```
Parallel execution with configuration on demand is an incubating feature.
:core:compileJava
:desktop:processResources UP-TO-DATE
:desktop:processTestResources UP-TO-DATE
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx/1.9.2/gdx-1.9.2.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d/1.9.2/gdx-box2d-1.9.2.jar
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:core:assemble UP-TO-DATE
:core:compileTestJava UP-TO-DATE
:desktop:compileJava
:core:processTestResources UP-TO-DATE
:core:testClasses UP-TO-DATE
:core:test UP-TO-DATE
:core:check UP-TO-DATE
:core:build UP-TO-DATE
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-lwjgl/1.9.2/gdx-backend-lwjgl-1.9.2.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.2/gdx-platform-1.9.2-natives-desktop.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-box2d-platform/1.9.2/gdx-box2d-platform-1.9.2-natives-desktop.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl/2.9.2/lwjgl-2.9.2.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl_util/2.9.2/lwjgl_util-2.9.2.jar
Download https://repo1.maven.org/maven2/com/badlogicgames/jlayer/jlayer/1.0.1-gdx/jlayer-1.0.1-gdx.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-windows.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-linux.jar
Download https://repo1.maven.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2/lwjgl-platform-2.9.2-natives-osx.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
:desktop:compileJava UP-TO-DATE
:desktop:classes UP-TO-DATE
:desktop:jar UP-TO-DATE
:desktop:assemble UP-TO-DATE
:desktop:compileTestJava UP-TO-DATE
:desktop:testClasses UP-TO-DATE
:desktop:test UP-TO-DATE
:desktop:check UP-TO-DATE
:desktop:build UP-TO-DATE

BUILD SUCCESSFUL

Total time: 19.737 secs
```
Kobalt log:
```
              __ __           __              __   __ 
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_  
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.682

  Downloaded http://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx/1.9.2/gdx-1.9.2.pom
  Downloaded http://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-lwjgl/1.9.2/gdx-backend-lwjgl-1.9.2.pom
  Downloaded http://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-lwjgl/1.9.2/gdx-backend-lwjgl-1.9.2.jar
  Downloaded http://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.2/gdx-platform-1.9.2.jar
  Downloaded http://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.2/gdx-platform-1.9.2.pom
  Downloaded http://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx/1.9.2/gdx-1.9.2.jar
          ╔═════════════════════╗
          ║ Building libgdxPlay ║
          ╚═════════════════════╝
*****
***** ERROR Unknown task: build
*****
BUILD FAILED: 1
```
Please ignore the build error on the second one. :P

Ran build on both of them by clearing their dependency caches.

**Comment by cbeust** [comment]
The error above seems to be coming from that fact that you invoked `./kobaltw build`.

What exactly is the error you're seeing with Kobalt?

**Comment by aneophyte** [comment]
Yes, sorry, did that by mistake.
The actual problem is that Kobalt doesn't resolve all of the dependencies, you can see that if you compare those logs.

**Comment by cbeust** [comment]
But what's the build error? What dependency is missing?

**Comment by aneophyte** [comment]
There's no build error. Build passes. The issue here arises when running the app, issues like ClassNotFoundException, not being able to locate native shared libraries, etc. That could be because it doesn't fetch all of the dependencies, as mentioned previously the project only worked when the related dependencies and native jars were added manually. The Gradle project didn't require explicit mentions or inclusions of those.

**Comment by cbeust** [comment]
Can you add the exact error to the issue? Hard to investigate without it.

**Comment by aneophyte** [comment]
I'll open up a new one, its gotten pretty confusing here.
