### ISSUE TITLE
Kobalt config/global working dir is inconsistent with Linux common practice

### ISSUE THREAD

**Issue by AlexCzar** [cbeust/kobalt#155]
Currently we have disposable kobalt-managed stuff in `~/.kobalt` and user-managed configuration stuff in `~/kobalt` which is as in the issue title.
I propose leaving disposable stuff in `~/.kobalt` and putting user-managed/config stuff in `~/.config/kobalt` as per freedesktop guidelines: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by cbeust** [comment]
Done, Kobalt now uses `~/.config/kobalt`.
