### ISSUE TITLE
New Feature: Add AsciiDoctor plugin

### ISSUE THREAD

**Issue by benignbala** [cbeust/kobalt#16]
Asciidoctor is becoming a reasonably popular documentation format. So, let's add a plugin to build it using asciidoctorj

I have started working on this. Will send in a PR sometime soon.

**Comment by cbeust** [comment]
Why a PR? If it's a plug-in, you can just upload it to JCenter and send me the info when it's done?

I'm planning to create a wiki where everybody can add the plug-in they wrote.

**Comment by benignbala** [comment]
Sounds good. Don't know why I never thought about it. :)

**Comment by cbeust** [comment]
Please keep a list of the obstacles you encounter writing the plug-in (doc, implementation, etc...) so I can improve things. Thanks!

**Comment by benignbala** [comment]
Sure, yes. And when I complete that plugin, I intend to write up a detailed documentation using asciidoctor, for Kobalt, built by Kobalt :) Hope you are all ok with that.

**Comment by benignbala** [comment]
And BTW, I am not very sure of the work flow that you have setup, but I guess you can mark this issue as closed. I'll inform you of the plugin through the dev list etc. Thanks

**Comment by cbeust** [comment]
Of course.

You might want to start from this example plug-in:

https://github.com/cbeust/kobalt-line-count

-- 
Cédric

**Comment by cbeust** [comment]
FYI, I expanded the documentation on how to write and debug plug-ins:

http://beust.com/kobalt/plug-in-development/index.html

**Comment by benignbala** [comment]
Thanks :)
