### ISSUE TITLE
"Unable to access jar file" on Windows

### ISSUE THREAD

**Issue by d3xter** [cbeust/kobalt#161]
Running kobalt-0.689 on Windows 10.

C:\Program Files\kobalt-0.689\bin\kobaltw.bat:

    @echo off
    java -jar  %~dp0/kobalt/wrapper/kobalt-wrapper.jar %*

Added kobalt-0.689\bin folder to $PATH and tried to run kobaltw.bat inside a project dir,
but running any command results in the following error message:

    Error: Unable to access jarfile C:\Program

**Comment by d3xter** [comment]
Using the following kobaltw.bat inside "kobalt-xxx\bin\" fixes this problem:

    @echo off
    java -jar  "%~dp0..\kobalt\wrapper\kobalt-wrapper.jar" %*

**Comment by cbeust** [comment]
Fixed.

**Comment by pabl0rg** [comment]
how should we fix this?  i am having the same problem with version .715 and .716:
```
./kobaltw assemble
Downloading https://github.com/cbeust/kobalt/releases/download/0.715/kobalt-0.715.zip 100.0%
[Wrapper] Downloaded https://github.com/cbeust/kobalt/releases/download/0.715/kobalt-0.715.zip
Error: Unable to access jarfile /Users/juanliska/.kobalt/wrapper/dist/0.715/kobalt/wrapper/kobalt-0.715.jar
```

**Comment by pabl0rg** [comment]
NVM.  I dealt with it by copying the kobalt-wrapper.jar from 
```
~/.kobalt/wrapper/dist/0.715/kobalt-0.715/kobalt/wrapper/kobalt-wrapper.jar
```
to the project's kobalt/wrapper folder
