### ISSUE TITLE
Initialise a new project with default build script andsource dirs based on language

### ISSUE THREAD

**Issue by benignbala** [cbeust/kobalt#17]
We probably should add a --lang arguments that takes the language of the porject as the parameter so that a project just about to be started can be initialised from kobalt

1) Create the build script for the appropriate language
2) Create src/main/$lang and src/test/$lang directory structures.

I'll send in a PR if this is ok

**Comment by cbeust** [comment]
I have more ambitious plans for this features: templates (known as archetypes in Maven terminology).

Basically, something like `./kobaltw --initWith kotlin` would create a hierarchy with a bunch of files to get you started.

**Comment by benignbala** [comment]
Ah, awesome. action4j or templates based on kotlin ?

**Comment by cbeust** [comment]
What's action4j?

I think each template would probably be a zip file with a hierarchy of
files, possibly post processed with some string replace.

-- 
Cédric

**Comment by benignbala** [comment]
I guess I forgot the exact name for the template engine in Java, action4j is what I remember. With respect to templates, I have seen people do it with generic template engnes line Cheetah in Python.
