### ISSUE TITLE
Running kobalt --init kotlin does not create project wrapper script

### ISSUE THREAD

**Issue by keslerm** [cbeust/kobalt#171]
When running kobaltw --init kotlin in a new project, it is not creating the kobaltw wrapper script in the local project directory which the documentation says it should be

>  From now on, you can just use ./kobaltw to build and you can ignore the kobaltw on your path, which is only useful to install Kobalt on new projects. Since you will now build each project with its own ./kobaltw command, they will use their own version of Kobalt.

**Comment by cbeust** [comment]
Can you walk me through the steps you followed?

**Comment by keslerm** [comment]
Sure!

1) Download latest release from github
2) Extract somewhere (~/kobalt)
3) CD into empty project folder (cd test_project)
4) Run ~/kobalt/bin/kobaltw --init kotlin

Ouptuts:

>             _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.739

> Template "kotlin" installed
> Now you can run either `./kobaltw test` or `./kobaltw run`

End up with
.kobalt/
kobalt/
.kobalt/

but no kobaltw

**Comment by cbeust** [comment]
Can you update to the current version (`kobaltw --update`, should be 0.743)
and try again?


-- 
Cédric

**Comment by keslerm** [comment]
Just downloaded 0.744 manually and when i try to run it

> └> ../kobalt-0.744/bin/kobaltw --init kotlin
Exception in thread "main" java.lang.IllegalArgumentException: Couldn't find kobalt.properties
	at com.beust.kobalt.wrapper.Main.maybeCreateProperties(Main.java:106)
	at com.beust.kobalt.wrapper.Main.getVersion(Main.java:40)
	at com.beust.kobalt.wrapper.Main.installAndLaunchMain(Main.java:45)
	at com.beust.kobalt.wrapper.Main.main(Main.java:15)

**Comment by cbeust** [comment]
Yes, 0.744 is bogus, I just deleted it, but you probably already had
downloaded it. 0.743 should be fine.


-- 
Cédric

**Comment by keslerm** [comment]
Okay here goes
```

┌[keslerm@panzerbox]-(~/applications)                                           
└> unzip ~/Downloads/kobalt-0.743.zip 
Archive:  /home/keslerm/Downloads/kobalt-0.743.zip
  inflating: kobalt-0.743/bin/kobaltw  
  inflating: kobalt-0.743/kobalt/wrapper/kobalt-0.743.jar  
  inflating: kobalt-0.743/kobalt/wrapper/kobalt-wrapper.jar  
┌[keslerm@panzerbox]-(~/applications)                                           
└> chmod +x kobalt-0.743/bin/kobaltw 
┌[keslerm@panzerbox]-(~/applications)                                           
└> mkdir test
┌[keslerm@panzerbox]-(~/applications)                                           
└> cd test
┌[keslerm@panzerbox]-(~/a/test)                                                 
└> ../kobalt-0.743/bin/kobaltw --version
Kobalt 0.739, Wrapper 0.739
└> ../kobalt-0.743/bin/kobaltw --update
......
Kobalt 0.739, Wrapper 0.743
└> ../kobalt-0.743/bin/kobaltw --version
Kobalt 0.739, Wrapper 0.743
┌[keslerm@panzerbox]-(~/a/test)                                                 
└> ../kobalt-0.743/bin/kobaltw --init kotlin
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.742
Template "kotlin" installed
Now you can run either `./kobaltw test` or `./kobaltw run`
┌[keslerm@panzerbox]-(~/a/test)                                                 
└> ls -alh
total 24K
drwxr-xr-x  6 keslerm keslerm 4.0K Apr 21 19:01 ./
drwxr-xr-x 10 keslerm keslerm 4.0K Apr 21 18:59 ../
drwxr-xr-x  2 keslerm keslerm 4.0K Apr 21 19:00 .idea/
drwxr-xr-x  4 keslerm keslerm 4.0K Apr 21 19:01 kobalt/
drwxr-xr-x  2 keslerm keslerm 4.0K Apr 21 19:00 .kobalt/
drwxr-xr-x  4 keslerm keslerm 4.0K Apr 21 19:01 src/

```

**Comment by cbeust** [comment]
Thanks, will look into this shortly.


-- 
Cédric

**Comment by cbeust** [comment]
In the meantime, just copy the `kobaltw` script from the distribution into your project root so you don't get stuck.

**Comment by mattibickel** [comment]
I do this, but the `kobaltw` script specifically says `$(dirname $0)/../kobalt`, so you either have to cut the `..` out or place `kobaltw` in the `kobalt` directory and call it from there. Just pointing it out.

**Comment by keslerm** [comment]
@mattibickel Have you tried with a new version? I just tried this with 0.756 and it looks like it puts the script there now

```
 ┌[keslerm@panzerbox]-(/m/s/p/test-project)                                                                                                          
└> ~/applications/kobalt-0.756/bin/kobaltw --init kotlin
              __ __           __              __   __ 
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_  
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.755



Template "kotlin" installed
Now you can run either `./kobaltw test` or `./kobaltw run`
┌[keslerm@panzerbox]-(/m/s/p/test-project)                                                                                                          
└> ls -alh
total 4.0K
drwxr-xr-x 1 keslerm keslerm  56 May  3 08:22 ./
drwx------ 1 keslerm keslerm 934 May  3 08:20 ../
drwxr-xr-x 1 keslerm keslerm   0 May  3 08:22 .idea/
drwxr-xr-x 1 keslerm keslerm  20 May  3 08:22 kobalt/
drwxr-xr-x 1 keslerm keslerm  36 May  3 08:22 .kobalt/
-rwxr--r-- 1 keslerm keslerm  81 May  3 08:22 kobaltw*
drwxr-xr-x 1 keslerm keslerm  16 May  3 08:22 src/
```
