### ISSUE TITLE
IDEA Plugin thinks Gradle project is Kobalt project

### ISSUE THREAD

**Issue by hoangtranwork** [cbeust/kobalt#198]
Environment:
* Windows 10
* IDEA 2016.1.2

Steps:

1. Make sure Kobalt plugin is 'not' installed
2. Create a brand new Gradle project
3. Run the `Build` task by clicking it in Gradle tab, IDEA will add a Run Configuration for that automatically (at this point everything is normal: https://db.tt/kvNAB99U).
4. Install Kobalt plugin (require restart IDEA and reopen project)
5. Now with the project reopen, clicking another Task, for e.g. `jar` in the Gradle Tab:

Expected:
- it run as a gradle task
- the Run-configuration that is automatically created is a Gradle one

Actual:
- it still run as a gradle task (OK),
- but the configuration that is created is a Kobalt's one https://db.tt/3uNaeDyU
As a confirmation, now if we click the green play button next to such newly created Kobalt task, it run as Kobalt https://db.tt/GkBe1Uio

**Comment by dmitry-zhuravlev** [comment]
It is a known bug at the moment.. Some fixed needs from JB side. We should wait until https://youtrack.jetbrains.com/issue/IDEA-156080 will be available in release versions of IDEA.

**Comment by cbeust** [comment]
The fix is deployed.
