### ISSUE TITLE
Is it possible to specify different dependencies for different productFlavor?

### ISSUE THREAD

**Issue by maxd** [cbeust/kobalt#204]
i.e. specify additional dependencies in `productFlavor` section:

```
dependencies {
    compile("X:X:1.0")
}


productFlavor("feature1") {
    dependencies {
        compile("A:A:1.0")
    }
}

productFlavor("feature2") {
        compile("B:B:1.0")
}
```

So, compilation of `feature1` should include `X` and `A` dependencies but `feature2` should include `X` and `B` dependencies.

Seems like right now the `kobalt` include all dependencies: `X`, `A`, `B` to all flavors.

**Comment by cbeust** [comment]
Not supported right now but it's definitely a useful feature, will add it.

**Comment by cbeust** [comment]
Deployed in the latest:

**Comment by cbeust** [comment]
Now available in the latest:
