### ISSUE TITLE
IDEA template should be updated

### ISSUE THREAD

**Issue by dmitry-zhuravlev** [cbeust/kobalt#208]
IDEA template (--init idea) should be updated to the new format.
The best way to get it for ".idea" folder is to generate Kobalt project via existing wizzard like explained in https://github.com/cbeust/kobalt/issues/201
Please note that paths in .idea/kobalt.xml should be initialized properly.

**Comment by cbeust** [comment]
In case you’d like to do this yourself, the files can be found in
src/main/resources/templates/idea.
​

-- 
Cédric

**Comment by dmitry-zhuravlev** [comment]
Thanks for pointing! @cbeust After looking on the code I rethink once again about necessity to have "--init idea" template and found that there is no way to generate data for project tree content which shown in tool window. This tree serialized in the binary format and stored in IDEA cashes. So in fact this template will generate project without this tree. User must reimport project from sources to have this tree. In result all which "--init idea" do will be reimported by IDEA and template becomes useless. But for example "--init kotlin" and then open project in IDEA with "import detached project" will lead to fully initialized project creation- the same result like "idea" template originally designed for.

**Comment by cbeust** [comment]
So basically, you think I should just remove the `idea` template from Kobalt?
