### ISSUE TITLE
Make Kobalt available uder SdkMan

### ISSUE THREAD

**Issue by ysb33r** [cbeust/kobalt#21]
I think it that it would ve very useful if Kobalt can be accessed in a similar way to Gradle via SdkMan.(https://github.com/sdkman/sdkman-java-sdk and http://sdkman.io/). Althought it's predecessor GVM, was mostly for tools in the Groovy environment, the new SdkMan aims to be far more reaching. 

There the ability to install Kobalt via the command-line sdkman interface would be very useful.

**Comment by cbeust** [comment]
Hi @ysb33r,

SDKMan still seems to be mostly for Groovy code, how would it help Kobalt users exactly?

**Comment by ysb33r** [comment]
As a use-case today I can do

```
sdk list gradle
```

WHich gives a list of available Gradle distributions, to which I can decide which ones I want to install
i.e.
```
sdk install gradle 2.7
```
If I decide to use another version temporarily in a console I simply do
```
sdk use gradle 2.5
```
This is not quite the same as the Gradle wrapper or the Kobalt wrapper which primary use is to reduce the overhead of installing a specific tool when building a project. (I really like the wrapper idea).

However, let's say that I notice some odd behaviour in example Kobalt 0.3, but I am not sure whether it is my project or the new version of Kobalt. In that case if I could do
```
sdk use kobalt 0.2
```
and re-run I can test the same with the 0.2 version.

You are right that there is a lot of Groovy tools in there, but that is purely because of its roots. I know @marcoVermeulen is strongly pushing to get some Scala tools in there too. No reason why Kobalt cannot get ahead of the curve IMO>

**Comment by marcoVermeulen** [comment]
Kobalt would be more than welcome on sdkman. We are preparing to do a rollout of many new non-groovy SDKs in the course of next week, including a complete bundle of Scala tools. However, we are not only limited to Groovy and Scala but welcome all SDKs (hence the name change).

It is also noteworthy that we are also providing a Vendor API that puts you in control of your own releases on sdkman. Please see details here:
http://sdkman.io/vendors.html

**Comment by cbeust** [comment]
@ysb33r Again, I'm not sure I understand the added value.

Right now, you can switch Kobalt versions instantly (just edit `kobalt-wrapper.properties`, or ask `kobaltw` to do it itself). On top of that, each project can use a different version (unclear if `sdk` allows that). This way, I'm also in control of the distribution, which allows me to switch hosts if I need to, manage outages, have access to stats, etc...

Asking users to first install `sdk` before they can install Kobalt is a barrier to adoption, in my opinion.

**Comment by benignbala** [comment]
@cbeust yes, each project can use a different version of gradle under sdk. When you have installed versions x, y and z of a tool under sdk, say gradle, you can simply say 

    sdk use gradle x 

and the gradle binary would point to the version x of that. Next instant if you choose to use version y, you can again do 

    sdk use gradle y 

and irrespective of your $PWD, gradle will point to version y of it. And I agree with @ysb33r 's point of view. It will be very useful to have kobalt under sdkman because for the same project, you could try with multiple versions of the build tool if the version of Kobalt pointed to by the wrapper script seems to have some as-yet-uncovered bug.

Also, sdkman will not be the only way to install kobalt. So, you won't be forcing users to install sdk before insall Kobalt. It is only an option, but a very convenient one if you are on a Unix system. And given that they are adding a lot of SDKs, I guess a lot more people will start using it now. In fact, I would **suggest that you should consider shipping kotlin and kobalt on sdkman** :)

**Comment by marc0der** [comment]
Well, send me a mail if you want kobalt published to sdkman. I will arrange you release API access.

**Comment by JasonKDarby** [comment]
+1

**Comment by benignbala** [comment]
Now, we have Ceylon on it, we should probably get kotlin and kobalt there.

**Comment by iamsteveholmes** [comment]
+1

Even if Kobalt is duplicates the sdkman functionality, I use sdkman to manage a number of my packages.  Maybe we can get Kotlin up there also.

**Comment by marc0der** [comment]
@cbeust for sure, we can have a chat about the details on the sdkman [gitter](https://gitter.im/sdkman/vendors) if you like.

**Comment by fwilhe** [comment]
Is this issue still active? Kotlin is on sdkman now, and I would find it convenient if kobalt were there too.

**Comment by cbeust** [comment]
Yes, Kobalt is still not on SdkMan.

-- 
Cédric

**Comment by marc0der** [comment]
I would love to host Kobolt on sdkman, but would need cooperation from @cbeust to help publish his releases.

**Comment by cbeust** [comment]
@marc0der Happy to work on that, what do I need to do?

**Comment by marc0der** [comment]
@cbeust It's a pretty simple integration, and can easily be tied into your release pipeline/process. You can find all the details on the [vendors page](http://sdkman.io/vendors.html) of our site.

I would also suggest we do a dry run release to our _dev_ environment first, then hook you up to our _prod_ servers once we are happy. Credentials can be obtained from me directly at the address given on the page.

**Comment by AlexCzar** [comment]
Any progress or plans about this integration?

**Comment by cbeust** [comment]
sdkman requires the zip file to have a certain format, which Kobalt doesn't
follow right now, so I need to carve out some time to do this since it has
implications on how the wrapper works.

In the meantime, Kobalt is available on Homebrew, can you get it from there?

-- 
Cédric
