### ISSUE TITLE
Build dependent projects if specifying project at command line

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#212]
If having
```
val p1 = project {...}
val p2 = project(p1) {...}
```
and running `./kobaltw p2:assemble` then only `p2` is assembled, but not `p1`.

Would expect that all dependent project are also assembled.
Otherwise the build may fail because p1 was never build before.
Or p2 may build with out-of-date artifacts of p1.

Also if having many projects in Build.kt (with deep project dependencies) then its nearly not possible to build a single project with all its dependencies.

**Comment by dmitry-zhuravlev** [comment]
> Would expect that all dependent project are also assembled.

Agree, I think Gradle also work in this way ("buildNeeded" "buildDependents" tasks). Also "p1:build" will trigger compile for the project in which p1 depends on.

**Comment by cbeust** [comment]
Deployed.
