### ISSUE TITLE
kobaltBuild\test-classes in javac classpath of 'compile' task

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#214]
The `compile` task passes `kobaltBuild\test-classes` to `javac` classpath, which it should not. IMO.

This is the javac command line (output with --log 2) of the project below:

`javac -d p1\kobaltBuild\classes -classpath D:\Projects\kobalt-sandbox\p1\kobaltBuild\classes;D:\Projects\kobalt-sandbox\p1\kobaltBuild\test-classes p1\src\main\java\p1.java`

```
val p1 = project {
	name = "p1"
	directory = name
}
```

**Comment by cbeust** [comment]
Oh yes that's weird.

-- 
Cédric

**Comment by DevCharly** [comment]
Could you please reopen this issue?

`test-classes` is back in javac classpath (0.885):

`javac -d p1\kobaltBuild\classes -classpath p1\kobaltBuild\classes;p1\kobaltBuild\test-classes p1\src\main\java\p1.java`

**Comment by cbeust** [comment]
Will be fixed in 0.886.
