### ISSUE TITLE
Incomplete javac classpath

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#215]
The output of a dependent project is not added to the javac classpath, if no dependencies are specified.

E.g. having p1 and p2 (depends on p1):
```
val p1 = project {
	name = "p1"
	directory = name
}

val p2 = project(p1) {
	name = "p2"
	directory = name
}
```
With this the javac command line for p2 is:
`javac -d p2\kobaltBuild\classes -classpath D:\Projects\kobalt-sandbox\p2\kobaltBuild\classes;D:\Projects\kobalt-sandbox\p2\kobaltBuild\test-classes p2\src\main\java\p2.java`

But after adding following (unused) dependencies to p2, javac classpath includes p1 (and unused jcommander):
```
	dependencies {
		compile("com.beust:jcommander:1.48")
	}
```

`javac -d p2\kobaltBuild\classes -classpath D:\Projects\kobalt-sandbox\p2\kobaltBuild\classes;D:\Projects\kobalt-sandbox\p2\kobaltBuild\test-classes;C:\Users\charly\.kobalt\repository\com\beust\jcommander\1.48\jcommander-1.48.jar;p1\kobaltBuild\classes p2\src\main\java\p2.java`

**Comment by DevCharly** [comment]
BTW is there a reason that `D:\Projects\kobalt-sandbox\p2\kobaltBuild\classes` is an absolute path, but `p1\kobaltBuild\classes` and `p2\src\main\java\p2.java` are relative?

**Comment by cbeust** [comment]
Should be fixed in the latest, can you try again?

**Comment by DevCharly** [comment]
Kobalt 0.793 reports: BUILD SUCCESSFUL :+1: 
Many thanks
