### ISSUE TITLE
Changing apt outputDir causes generated classes to not be found

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#220]
1) Clone my test repo: https://github.com/sargunster/annotations
2) `./kobaltw run` -- it works
3) Add the following to `p2` in `Build.kt`:
```
    apt {
        outputDir = "generated/sources/apt"
    }
```
4) `./kobaltw clean`
5) `./kobaltw run` -> `error: cannot find symbol`

**Comment by cbeust** [comment]
Fixed in latest.
