### ISSUE TITLE
Kobal process does not quit on exceptions

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#229]
If an exception (or Throwable) occurs, the kobalt process does not exit. It hangs around waiting for manual kill.

I think it would be better to catch Throwable, report "BUILD FAILED" and exit the process.

Here is a Build.kt to reproduce the issue:
```
val p1 = project {
	throw RuntimeException("test")
}
```

**Comment by DevCharly** [comment]
Found a simple fix :wink:

**Comment by cbeust** [comment]
Just merged it, thanks!
