### ISSUE TITLE
Too many "Building projectX" boxes in output

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#231]
The output always contains "Building projectX" boxes for all projects in Build.kt, even if I build only a single project (e.g. `./kobaltw project1:assemble`). This is confusing...

Would prefer to see "Building projectX" boxes only for projects, which are involved in current build (given at command line and dependent projects).

**Comment by cbeust** [comment]
Fixed in latest.

**Comment by DevCharly** [comment]
Thanks for the fix, but now it processes projects in the wrong order...

When building the below Build.kt with `kobaltw assemble`, the order is p1, p2 and p3, which is OK.
But using `kobaltw p3:assemble`, the order is p3, p2 and p1.

```
val p1 = project { name = "p1" }
val p2 = project(p1) { name = "p2" }
val p3 = project(p2) { name = "p3" }
```

**Comment by cbeust** [comment]
Oops you're right, going to add a test for this.

Should be fixed in the latest.

**Comment by DevCharly** [comment]
Yes, looks good now :+1: 
Thanks

**Comment by DevCharly** [comment]
@cbeust just discovered two problems on a complex project:
* some projects are built more than once
* a project is built before a project that it depends on

Here is a test Build.kt with a `build` task, which checks whether dependsOn projects are built:
```kotlin
import com.beust.kobalt.*
import com.beust.kobalt.api.*
import com.beust.kobalt.api.annotation.Task

val p1 = project { name ="p1" }
val p2 = project { name ="p2" }
val p3 = project { name ="p3" }
val p4 = project { name ="p4" }
val p5 = project { name ="p5" }
val p6 = project(p5) { name ="p6" }
val p7 = project(p5) { name ="p7" }
val p8 = project { name ="p8" }
val p9 = project(p6, p5, p2, p3) { name ="p9" }
val p10 = project(p9) { name ="p10" }
val p11 = project { name ="p11" }
val p12 = project(p11, p10, p9, p7, p1) { name ="p12" }
val p13 = project(p12, p9, p8, p4) { name ="p13" }
val p14 = project(p12, p13) { name ="p14" }

@Task(name = "build")
fun taskBuild(project: Project) : TaskResult {
    if (!areAllDependsOnProjectsBuilt(project))
        System.out.println("==== FAIL ====")

    project.projectProperties.put("built", true)
    return TaskResult()
}

fun areAllDependsOnProjectsBuilt(project: Project) : Boolean {
    project.projectExtra.dependsOn.forEach {
        if (it.projectProperties.get("built") == null) {
            System.out.println("---- Project ${it.name} not yet built ----")
            return false
        }
        if (!areAllDependsOnProjectsBuilt(it))
            return false
    }
    return true
}
```
When running this Build.kt with `./kobaltw p14:build` the output is (boxes removed):
```
───── p5:build
───── p5:build
───── p3:build
───── p2:build
───── p5:build
───── p6:build
───── p9:build
───── p4:build
───── p8:build
───── p9:build
───── p12:build
---- Project p11 not yet built ----
==== FAIL ====
───── p1:build
───── p7:build
───── p9:build
───── p10:build
───── p11:build
───── p13:build
───── p12:build
───── p14:build
```
Some projects are built more than once (e.g. `p5`, `p9` or `p12`)
And `p12` is built before `p11`

When running with `./kobaltw build` (without project), everything works fine

**Comment by cbeust** [comment]
Thanks for the great bug report, will take a look.

**Comment by cbeust** [comment]
Fix deployed.

**Comment by cbeust** [comment]
Fix deployed.

**Comment by cbeust** [comment]
FYI, here is the updated test:  https://github.com/cbeust/kobalt/blob/master/src/test/kotlin/com/beust/kobalt/internal/BuildOrderTest.kt#L54
