### ISSUE TITLE
Ability to debug Build.kt script

### ISSUE THREAD

**Issue by dmitry-zhuravlev** [cbeust/kobalt#232]
Actually ability to debug `Build.kt` file (not only Kobalt internals like Manifest.attributes) will be a great feature. User can have some `fun complexMethod` inside `Build.kt` and debug it.
The problem why it is not working at the moment is the way like Kobalt compile `Build.kt` file.
It saves to temporary dir with some random `kobalt-XXXXX.kt` name and compile it and pack inside `buildScript.jar`. The result classes will be the following:

![photo_2016-06-06_15-57-41](https://cloud.githubusercontent.com/assets/6297697/15822602/6a26a926-2bff-11e6-9ab8-0228fad04ee1.jpg)

But the original source file still `Build.kt` and debug doesn't catch it.

It should use exactly `Build.kt` source file to make debug possible. Kobalt should compile and pack into `buildScript.jar` the actual Build.kt file, so the resulting jar will be the following:

![photo_2016-06-06_16-08-29](https://cloud.githubusercontent.com/assets/6297697/15822877/eba87ff0-2c00-11e6-96d4-31c5c4334f38.jpg)

 @cbeust Any thoughts how to avoid compile and packaging temporary sources?

**Comment by dmitry-zhuravlev** [comment]
Problem can be solved if in `BuildFileCompiler` use `sourceFiles(listOf(buildFile.realPath.toFile().absolutePath))` instead of
`sourceFiles(listOf(buildFile.path.toFile().absolutePath))`

@cbeust Do we really need this temporary source file like stated in comment of `BuildFileCompiler:90` ?

**Comment by cbeust** [comment]
The two steps are necessary. Here is how it works:

- Kobalt extracts the `plugin()` and `repos()` lines found in `Build.kt` in a separate `.kt` file and compiles it into `preBuildScript.jar`. This allows me to look up these plug-ins and repos and download the jar files if necessary.

- Then Kobalt builds the actual `Build.kt` after adding the jar files downloaded in the previous path on the classpath. This results in `buildScript.jar`.

Still, we should be able to tell IDEA that the source file for both these jar files is `Build.kt`, shouldn't we?

**Comment by dmitry-zhuravlev** [comment]
> Still, we should be able to tell IDEA that the source file for both these jar files is Build.kt, shouldn't we?

User can put breakpoints only on `Build.kt` source. He knows nothing about kobalt-XXXXX.kt in temp directory. So the only way to make it work is to put in `buildScript.jar` classes compiled agains `Build.kt` not the temporary one.

You ca check how it works with fix in `BuildFileCompiler` mentioned by my above.
With this user can debug almost all in `Build.kt` take a look on this:

![image](https://cloud.githubusercontent.com/assets/6297697/15824406/b480767a-2c07-11e6-860e-e28a16adcb52.png)

**Comment by cbeust** [comment]
Ah I see.

I think there was a reason why I decided to copy `Build.kt` in a temporary directory and compile that one instead of the original one but I can't remember why. Maybe some locking issue.

I'll make the change you suggested, we'll see how it goes.

**Comment by cbeust** [comment]
I can't find this code at line 90 though, can you double check which one you mean?

**Comment by cbeust** [comment]
(or feel free to send a PR)

**Comment by dmitry-zhuravlev** [comment]
It is really cool to debug almost all code in `Build.kt`. It's killer feature :)
