### ISSUE TITLE
Pack sources in kobalt.jar

### ISSUE THREAD

**Issue by dmitry-zhuravlev** [cbeust/kobalt#237]
It would be a good for user to have sources for Kobalt DSL.
E.g. read about `dependencies` directive (and the rest directives\properties in `Build.kt`) could be much easier for user because he could explore code and javadoc directly from IDEA editor while writing `Build.kt` file.

**Comment by cbeust** [comment]
Agreed but is there another we can achieve this than packing the sources in `kobalt.jar`? 

For example, the plug-in creates the `Build.kt` and makes it depend on the Library `kobalt.jar`. That library can be attached to sources, which the IDEA plug-in could find in `~/.kobalt/repository/com/beust/kobalt-XXX/...*sources.jar`.

Is this doable?

**Comment by cbeust** [comment]
Yeah, it wouldn't be a big deal to package the sources in `kobalt.jar` I guess.

Does IDEA require the source files to be in a certain location in the jar file? I'm guessing at the root?

Can you experiment with that (add the sources manually to `kobalt.jar`) and report back?

**Comment by dmitry-zhuravlev** [comment]
I guess source files in the same places (packages) with classes will be enough. But I'll recheck.

**Comment by dmitry-zhuravlev** [comment]
Yep, sources can be packaged in the same places with class files. However some small changes needed in IDEA plugin to attach this sources. I'll do this changes in plugin.

**Comment by dmitry-zhuravlev** [comment]
@cbeust 
I think that we need to pack sources inside `kobalt-{version}.zip` distribution. Firstly we need to do the following: 
1) `kobalt-plugin-api-{version}-sources.jar` and `kobalt-{version}-sources.jar` should be packaged together and named `kobalt-{version}-sources.jar`
2) Resulted `kobalt-{version}-sources.jar` should be placed inside `kobalt-{version}.zip/kobalt-{version}/kobalt/wrapper`

IDEA plugin will automatically pick up this sources and attached to the `kobalt.jar` library.


Actually I tried to do the mentioned points in Kobalt `Build.kt` directly by doing something like:
```
       jar {
            name = "$projectName-$version-sources.jar"
            include("$directory/src/main/kotlin", "${kobaltPluginApi.directory}/src/main/kotlin")
        }
```
but this will not work.

@cbeust any tips how to do it?

**Comment by dmitry-zhuravlev** [comment]
Implemented in some straightforward way: https://github.com/cbeust/kobalt/pull/411
