### ISSUE TITLE
compilation (annotation, redeclaration) errors with kobalt > 0.793

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#240]
I couldn't reproduce this with my mixed-example project, but on my main project at work, which mixes java and kotlin, I get a variety of compile errors if i use kobalt > 0.793

Error descriptions by Kobalt version (I changed nothing but the Kobalt version between each attempt):

0.793
All good. Project compiles, tests pass.

0.795 - 0.803
during java compilation:
```warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'```

0.804 - 0.810
during kotlin compilation:
```error: redeclaration: AutoRecover``` 
(AutoRecover is the first class that it tries to compile)

**Comment by pabl0rg** [comment]
@cbeust is it now required to separate java and kotlin files into separate directories?  I have been using java and kotlin files in the same directory as it makes it easier to work in the IDE when only parts of a package have been converted to Kotlin.

**Comment by cbeust** [comment]
No, Kobalt doesn't care where these files are. Each compiler will locate the files it can compile in all the `src` directories.

**Comment by cbeust** [comment]
Can you point me to your failed build?

**Comment by pabl0rg** [comment]
I managed to get my example project to fail in the same way as the other project that i can't share.

https://github.com/pabl0rg/kobalt-mixed-example

If you comment-out line 24 in KExample.kt, the project builds with Kobalt 0.810 (kotlin 1.0.2) but with that line, you have to use 0.793 or earlier (kotlin 1.0.0)

**Comment by cbeust** [comment]
Note: the fix is not deployed yet, there's one more issue with it.

**Comment by cbeust** [comment]
Fixed in latest.
