### ISSUE TITLE
Better support for "project related tasks"

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#244]
Not sure whether this is a feature request or a bug report...

Normally in Kobalt, when defining a task, it is registered for all projects in Build.kt.
However I have a plugin that uses ITaskContributor to define a dynamic task for a single (or multiple) project(s), but not for all projects.

The idea is to have something like this:
```kotlin
val p = project {
   task("mytask", dependsOn="assemble") {
    // do something
  }
}
```

Here is demo how the plugin adds a dynamic task to a single project:
```kotlin
import com.beust.kobalt.TaskResult
import com.beust.kobalt.api.*
import com.beust.kobalt.api.annotation.AnnotationDefault

class TaskOnProjectPlugin : BasePlugin(), ITaskContributor {
    override val name = "TaskOnProjectPlugin"

    companion object {
        const val PROJECT = "pp3"
    }

    override fun accept(project: Project): Boolean {
        // make sure that dynamic task is added to TaskManager only for single project
        return project.name == PROJECT
    }

    override fun tasksFor(project: Project, context: KobaltContext): List<DynamicTask> {
        if (project.name != PROJECT)
            return emptyList()

        // add "mytask" for project "pp3"
        return arrayListOf(DynamicTask(this, "mytask", "", AnnotationDefault.GROUP,
                project,
                closure = { project ->
                    System.out.println("#### mytask on ${project.name} ####")
                    TaskResult()
                }))
    }
}
```
The plugin adds a dynamic task `mytask` to project `pp3`.

Build.kt:
```kotlin
import com.beust.kobalt.*

val plug = plugins(file("out/production/plugin"))

val pp1 = project { name = "pp1" }
val pp2 = project(pp1) { name = "pp2" }
val pp3 = project(pp2) { name = "pp3" }
```

Using `./kobaltw pp3:mytask` works fine if `pp3` does not depend on other projects.
But if `pp3` depends on other projects (as in the above Build.kt), I get an `ERROR Unknown task: TaskInfo(id=pp1:mytask)` because `pp1`does not have a `mytask`

Same error happens when using `./kobaltw mytask`

Ideally Kobalt could simply skip projects that do not have `mytask`, but still process projects it depends on. E.g. if `mytask`is defined for `pp1`and `pp3` (in the above Build.kt), then `./kobaltw pp3:mytask` could process `pp1:mytask` and `pp3:mytask` and silently ignore the fact that `pp2:mytask` does not exist.

The message `ERROR Unknown task: ...` could occur if a task passed at command line or a task in dependsOn/reverseDependsOn/etc does not exist.

**Comment by cbeust** [comment]
It's definitely a bug that Kobalt expects a task to exist on one project just because it exists on another, so I need to fix that (I didn't take dynamic tasks into account when I wrote this code).

**Comment by DevCharly** [comment]
Great :+1: 

Regarding dynamic tasks: there is some code in `TaskManager.installDynamicTasks()` that I don't understand. The class `DynamicTask` already has a `project` value, but you iterate over all projects and register the task for all project, which accept it. This is the line:
https://github.com/cbeust/kobalt/blob/master/modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/TaskManager.kt#L422

Why not remove this line and use `task.project` at next line?

**Comment by cbeust** [comment]
Indeed, this should work. Can you try it and if the tests pass, send a PR?

-- 
Cédric

**Comment by DevCharly** [comment]
ok
