### ISSUE TITLE
Doc missing example command generating IDEA files?

### ISSUE THREAD

**Issue by saltnlight5** [cbeust/kobalt#246]
Hi, What is the command to run to generate IDEA project files? It appear the step 5 in Getting started guide is missing this instruction.(see http://beust.com/kobalt/getting-started/index.html#generate-idea-files)

Googling around, it seems I should able to run `kobalt --init idea`, but this template no longer exists in Kobalt 0.808 ?

```
Zemians-Air:hello-kotlin zemian$ ./kobaltw --version
Kobalt 0.808, Wrapper 0.808

Zemians-Air:hello-kotlin zemian$ ./kobaltw --init idea
***** WARNING Couldn't find any template named idea

Zemians-Air:hello-kotlin zemian$ ./kobaltw --listTemplates
  Plug-in: Kobalt
    "java"		Generate a simple Java project
    "kotlin"		Generate a simple Kotlin project
    "kobaltPlugin"		Generate a sample Kobalt plug-in project
```

**Comment by cbeust** [comment]
Correct, I removed it since you can now generate a full project directly from IDEA by importing the project. I forgot to update the doc, which I just did:

http://beust.com/kobalt/getting-started/index.html#import-in-idea

Sorry for the confusion!
