### ISSUE TITLE
Incremental dynamic tasks

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#256]
Like to use Kobalts "incremental tasks" feature in dynamic tasks (`interface ITaskContributor`), but it seems that this is not yet support, right?

**Comment by cbeust** [comment]
Correct. Do you need it?

You can do it yourself right now with `IncrementalManager.toIncrementalTaskClosure`, which converts a method that returns an `IncrementalTaskInfo` into a regular task, but I probably don't want to expose this method so it's better if I just add a new contributor called `IIncermentalTaskContributor`.

Would that help?

**Comment by DevCharly** [comment]
Yes. need it for a plugin.
`IIncrementalTaskContributor` would be great.
Don't like invoke internal methods that maybe change/break in the future.

**Comment by cbeust** [comment]
Done. The new actor is called `IIncrementalTaskContributor`:

https://github.com/cbeust/kobalt/blob/master/modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/api/IIncrementalTaskContributor.kt

It's available in 0.837.

Let me know how it works for you.

**Comment by DevCharly** [comment]
Cool, thanks, will try...

**Comment by DevCharly** [comment]
Works, thanks :+1:

**Comment by cbeust** [comment]
Great. I'm curious to see what you're working on.

-- 
Cédric
