### ISSUE TITLE
"install" task runs although there is no "install" directive in Build.kt

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#258]
The documentation at http://beust.com/kobalt/plug-ins/index.html#install describes
> If you don't specify any install directive, then the install task will do nothing on your project when invoked.

but in reality it always copies `kobaltBuild\libs` to `libs`.

IMO it should do nothing if there is not install directive.

**Comment by cbeust** [comment]
Agreed.

-- 
Cédric

**Comment by cbeust** [comment]
Actually I'm going to slightly revise my stance. This looks similar to [this issue](https://github.com/cbeust/kobalt/issues/253).

The general question is whether a task should run if the user didn't specify a directive for it. This applies for both the "test" task and the `test{}` directive and "install" and `install{}`.

For this one, I think the task should install the artifact in `libs` even without `install{}`, so I'm more tempted to rectify the documentation than changing the current behavior.

What do you think?

**Comment by DevCharly** [comment]
That makes sense. Then better change the doc :+1:

**Comment by cbeust** [comment]
Done.
