### ISSUE TITLE
Add a Kobalt formula on homebrew

### ISSUE THREAD

**Issue by mokkun** [cbeust/kobalt#26]
It would be really nice to be able to install Kobalt through homebrew, not to say easier. :)

**Comment by cbeust** [comment]
Yup, I'll make Kobalt available on Homebrew and SDKMan eventually.

**Comment by mokkun** [comment]
@cbeust would it be okay if I look into this?

**Comment by cbeust** [comment]
@mokkun Thanks but it's already in progress and almost done!

Here's the PR:  https://github.com/Homebrew/homebrew/pull/49392

**Comment by mokkun** [comment]
Yeah, just found it while doing a `brew search kobalt`. Good job! :)

**Comment by cbeust** [comment]
Done!
