### ISSUE TITLE
"clean" task reports "WARNING Couldn't delete .\kobaltBuild"

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#260]
When running the `clean` task (from IDEA), sometimes I get `WARNING Couldn't delete .\kobaltBuild` and `kobaltBuild` directory is not deleted (but it is empty). Running `clean` task again then removes `kobaltBuild` directory.

Have not yet found a way to reproduce this...

**Comment by DevCharly** [comment]
Can reproduce it now: The Windows explorer causes the problem if I have kobaltBuild (or some sub-directory) selected in the explorer tree.

Closing because think that this can't be solved...

**Comment by cbeust** [comment]
Yes. This only happens on Windows and only if another process is currently
locking that directory. Not much I can do about this.

-- 
Cédric
