### ISSUE TITLE
Add support for mavenLocal()

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt#264]
- The local repo is specified in Kobalt's config file (`~/.config/kobalt/settings.xml`).
- The repo can be referenced with the directive `mavenLocal()`:

    val r = repos(mavenLocal())

- The task `publishToMavenLocal` will deploy the artifact to it.

**Comment by ethauvin** [comment]
Before build look for ``<localRepository>path/to/some/dir</localRepository>`` in:

1. ``${user.home}/.m2/settings.xml``
2. ``${maven.home}/conf/settings.xml``

Default value is ``<localRepository>${user.home}/.m2/repository</localRepository>`` per [Maven Settings Reference](https://maven.apache.org/settings.html).

Also potentially provide global override in ``~/.config/kobalt/settings.xml``.

**Comment by ethauvin** [comment]
As requested by @cbeust my maven's settings files for Windows and Linux, pointing to my local repository.

[win-maven-settings.xml.txt](https://github.com/cbeust/kobalt/files/354783/win-maven-settings.xml.txt)
[linux-maven-settings.xml.txt](https://github.com/cbeust/kobalt/files/354784/linux-maven-settings.xml.txt)

**Comment by cbeust** [comment]
Inline file for convenience:

**Comment by cbeust** [comment]
Update on this issue:

[x] Task "publishToMavenLocal"
[x] Directive `localMaven()` to reference that location in the build file
[x] Default is `~/.kobalt/localMavenRepo`
[x] The default can be overridden in `~/.config/kobalt/settings.xml` 

[ ] Allow this default to be overridden in the build file
[ ] Look up existing Maven settings and use those if found
