### ISSUE TITLE
Timestamp checksums do not work when renaming a single file

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#267]
When I rename a single resource file (in IDEA or in Explorer), then the name changes but the modification time of the file does not change. Then the (incremental) `compile` task does not start...

To solve this, we could include the filename in the checksum calculation.
To make it even more reliable, we could also include the file size.

What do you think?

**Comment by DevCharly** [comment]
> To solve this, we could include the filename in the checksum calculation.

To be precise: with "filename" I mean `file.path`

**Comment by cbeust** [comment]
Good point. This would be just a matter of adjusting the `toBytes` default value in `Md5.kt` to include the path of the file:

```
        fun toMd5Directories(filesOrDirectories: List<File>,
                toBytes: (File) -> ByteArray = { it.lastModified().toString().toByteArray() } ): String? {
```

Can you send a PR?

**Comment by DevCharly** [comment]
Sure

**Comment by DevCharly** [comment]
Done, but there is an additional problem: `src/main/resource` is not included in the checksum. Only `src/main/java` and `src/main/kotlin`
