### ISSUE TITLE
Plugin tasks are executed out of order.

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#276]
![capture](https://cloud.githubusercontent.com/assets/705618/16755238/2b7abd4a-47af-11e6-9a54-48f204d29717.PNG)

Project [here](https://github.com/ethauvin/kobalt-exec).

**Comment by cbeust** [comment]
Deployed.

**Comment by cbeust** [comment]
My fix wasn't good enough, reverted it.

**Comment by cbeust** [comment]
Should be fixed now.
