### ISSUE TITLE
mustache.java: java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by mokkun** [cbeust/kobalt#28]
Kobalt uses [mustache.java](https://github.com/spullara/mustache.java) which requires Java 8. When running the below steps with Java 7, an error is thrown.

### Steps
1. Ensure that Java 7 is the current Java version.
2. [Download Kobalt](https://github.com/cbeust/kobalt/releases/latest) and unzip the file (`$KOBALT_HOME`).
3. Change to a existing Java project directory and execute `$KOBALT_HOME/kobaltw --init`.

### Actual
The following error message is displayed.
```
Downloading https://dl.bintray.com/cbeust/generic/kobalt-0.208.zip 100.0%
[Wrapper] Downloaded https://dl.bintray.com/cbeust/generic/kobalt-0.208.zip
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.208

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/mustachejava/DefaultMustacheFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.beust.kobalt.ProjectGenerator.run(ProjectGenerator.kt:73)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:109)
	at com.beust.kobalt.Main.access$runWithArgs(Main.kt:43)
	at com.beust.kobalt.Main$run$1.invoke(Main.kt:72)
	at com.beust.kobalt.Main$run$1.invoke(Main.kt:43)
	at com.beust.kobalt.misc.BenchmarksKt.benchmark(Benchmarks.kt:5)
	at com.beust.kobalt.Main.run(Main.kt:69)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:40)
	at com.beust.kobalt.MainKt.main(Main.kt:23)
```

### Expected
A friendly error message telling the user that Java 8 is required in order to use Kobalt. The same should also be mentioned in the install guide.

### Environment
Operational System
`OSX 10.11.1 (15B42)`

Java
```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by cbeust** [comment]
Use 0.213, the version you're using was accidentally compiled with 1.8 but
Kobalt supports 1.7+.

-- 
Cédric

**Comment by mokkun** [comment]
I've tested it and confirm that it does work with 1.7 now. I'll close this issue. Thanks :)

**Comment by codeslubber** [comment]
I think this is happening again. Used 0.231 and got this with 1.7.

![kobalt-error](https://cloud.githubusercontent.com/assets/603642/11048127/e9d4d090-86ea-11e5-940f-4afcaef8034c.png)

**Comment by cbeust** [comment]
The banner is saying you're using 0.208?

**Comment by cbeust** [comment]
You are running the 0.231 wrapper but it will run whatever your local `kobalt/wrapper/kobalt-wrapper.properties` says. Make sure that property file says 0.231.

**Comment by codeslubber** [comment]
I didn't have anything installed prior to running this? was just following the instructions from the page: downloaded the zip, exploded it and went over to the project dir.

**Comment by cbeust** [comment]
You must have had at least 0.208, look into your `~/.kobalt/wrapper/dist`.

Are you saying there is no `kobalt/wrapper/kobalt-wrapper.properties` file in the same directory you ran `kobaltw` from?

**Comment by codeslubber** [comment]
The properties file does have 0.230 in it? in /usr/local/kogalt/kobalt/wrapper.

**Comment by codeslubber** [comment]
Wow, off of home there is a list file with 0.208 in it?? Where did that come from? I must be having a Caligari moment here, I swear I never installed this before!

**Comment by codeslubber** [comment]
Deleted everything and reran the init and that is what installed 0.208.

**Comment by cbeust** [comment]
You're right. I'm seeing the same thing you do after a clean download, I think the wrapper must have baked in the 0.208 number inside it. I'll update it.

**Comment by codeslubber** [comment]
Great thanks Cedric!

**Comment by cbeust** [comment]
Pretty mystified where this 0.208 is coming from right now, still looking.

**Comment by cbeust** [comment]
Ok I think I know what's going on. I thought that when I upload a new release to github, I just select the file and press "Ok". But if I do that before the file has been uploaded, it never gets uploaded. So github ends up offering only its own zip files, which are the sources of the repository. Not at all whatI want.

If I wait for the zip to be uploaded, you will now see:

![image](https://cloud.githubusercontent.com/assets/92322/11049573/13e793a0-86f4-11e5-8a1f-31548fa10aa2.png)

The .zip file you want is the first one, not the source code.

Try again (0.233) and let me know if this fixes it for you.

**Comment by codeslubber** [comment]
Ah, ok sounds good, I was wondering about that. Sorry, I should have gone back and looked again after.

**Comment by codeslubber** [comment]
Uh, so this time it did download 0.233 but alas:

![kobalt-233-error](https://cloud.githubusercontent.com/assets/603642/11049666/d8ae8324-86f4-11e5-8ba7-6b5cffc51d33.png)

**Comment by codeslubber** [comment]
The wrapper/dist off ~ looks fine: 0.233.

**Comment by codeslubber** [comment]
java version "1.7.0_60-ea"

**Comment by cbeust** [comment]
So it looks like Mustache is compiled with 1.8... I didn't realize that :(

Guess that makes Kobalt 1.8 only for now. I'll see if I can fix that, I'd like to shoot for 1.7.

For now, you'll have to use 1.8, is that feasible for you?

**Comment by codeslubber** [comment]
I installed 1.8 as soon as I hit this but the condition of J on the mac is somewhere between Fukushima and Dante's Inferno. It installed and then new terminal happily reported 1.7. My highest voted question on SO is how to uninstall 8 from the mac so... I am sure I can figure out what the latest way is to change the default VM and hopefully JetBrains has addressed their issues with 8. Thanks again Cedric. Looking forward to using this. Great job!

**Comment by codeslubber** [comment]
Done. Thanks again.

**Comment by cbeust** [comment]
Join us on slack if you have more questions!

**Comment by cbeust** [comment]
Pinging @spullara. Sam, would you be willing to push an 1.7 version of mustache-java?
