### ISSUE TITLE
Cannot import kobalt project into IntelliJ

### ISSUE THREAD

**Issue by derkork** [cbeust/kobalt#282]
When I try to import a simple project into IntelliJ, I get an error message reading "java.net.ConnectException: failed to connect to localhost/fe80:....." (see attached screenshot).

![image](https://cloud.githubusercontent.com/assets/327257/16907297/c62575de-4cc2-11e6-9793-b53f7b5d6ef9.png)

Here is the log.

[kobalt_idea.log.txt](https://github.com/cbeust/kobalt/files/368452/kobalt_idea.log.txt)

And here is the kobalt version info:

```
➜  simplegen kobaltw --version
Kobalt 0.666, Wrapper 0.853

```

Plugin version is 1.114

kobaltServer.properties

```
#
#Mon Jul 18 08:51:35 CEST 2016
pid=70003
port=1234

```

And the process seems to be running:

`j.thomae        70003   0.0  0.5  7096156  79532   ??  S     8:51AM   0:02.98 /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath /Users/j.thomae/.kobalt/wrapper/dist/kobalt-0.853/kobalt/wrapper/kobalt-0.853.jar com.beust.kobalt.MainKt --log 3 --force --dev --server
`

But the port doesn't seem to be bound:

```

➜  .kobalt lsof -i tcp:1234
# nothing here

```

**Comment by cbeust** [comment]
ping @dmitry-zhuravlev

**Comment by dmitry-zhuravlev** [comment]
Hi Jan,
Do you try to import some Kobalt project generated via plugin's wizzard? Does this problem always persist for you or it was just one case?

**Comment by derkork** [comment]
I created the kobalt project on the console using the kobalt wrapper's
`kobaltw --init kotlin`. Then I opened the project in IntelliJ and got a
notification that the project can be imported. Then I click on it and the
import dialog opens. From there I try to import the project but always get
this error message. I haven't been able to import the project yet.

2016-07-19 9:10 GMT+02:00 Dmitry Zhuravlev <notifications@github.com>:

**Comment by dmitry-zhuravlev** [comment]
Make some changes in plugin regarding the latest API changes (affect the latest IDEA 2016.2) https://github.com/cbeust/kobalt-intellij-plugin/commit/662fb6782711f2c8e0a17470928d4fbe1dc3708c
However at the moment Kobalt fail to resolve dependencies via simple REST call:
http://localhost:1234/v0/getDependencies

returns: 

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /v0/getDependencies. Reason:
<pre>    java.lang.NoSuchMethodError: org.apache.http.client.utils.URIUtils.extractHost(Ljava/net/URI;)Lorg/apache/http/HttpHost;</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>
</body>
</html>

@cbeust Any thoughts?

**Comment by cbeust** [comment]
Mmmh weird, looking.

-- 
Cédric


On Tue, Jul 19, 2016 at 11:07 AM, Dmitry Zhuravlev <notifications@github.com

**Comment by cbeust** [comment]
Oh but why is it asking the `v0` endpoint? I don't think we're using it any more, it's all websockets going on `v1`, correct?

**Comment by derkork** [comment]
Just FYI, the problem is still there with the latest wrapper version .859.

**Comment by dmitry-zhuravlev** [comment]
I used 'v0' endpoint just for manual checking... I'll debug more deeply.

**Comment by cbeust** [comment]
@dmitry-zhuravlev Ok, let me know if you need me to debug something into Kobalt itself.

**Comment by dmitry-zhuravlev** [comment]
The problem was in settings format. It seems that the first tag changed from `kobalt-settings` to `kobaltSettings`. This lead to server fail while trying to start:

`Exception in thread "main" javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"kobalt-settings"). Expected elements are <{}kobaltSettings>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.`

I changed settings in my ~/.config/kobalt dir and it helps me to resolve the original problem.
However other users should know that structure of settings was changed. @cbeust Was there any intentions to change settings root tag?

**Comment by cbeust** [comment]
Yes, I just discussed this change in the channel this morning.

I'll deploy a new IDEA plug-in to bump Kobalt to the latest.


-- 
Cédric


On Thu, Jul 21, 2016 at 11:25 AM, Dmitry Zhuravlev <notifications@github.com

**Comment by dmitry-zhuravlev** [comment]
But only bump to the latest not enough. Maybe Kobalt should migrate somehow from old format to the new one? Because at the moment user should manually edit settings...

**Comment by cbeust** [comment]
I thought about that but decided that it wasn't worth the effort since I
don't expect too many people to have this `settings.xml` file at this point

Obviously, I would never do that after 1.0 :-)


-- 
Cédric


On Thu, Jul 21, 2016 at 11:32 AM, Dmitry Zhuravlev <notifications@github.com

**Comment by dmitry-zhuravlev** [comment]
Yep, sounds reasonable ;-)

**Comment by cbeust** [comment]
New plug-in deployed.

-- 
Cédric


On Thu, Jul 21, 2016 at 11:36 AM, Dmitry Zhuravlev <notifications@github.com

**Comment by dmitry-zhuravlev** [comment]
Oh, redeploy it please once again. Just removed obsolete classes which cause of Tasks node duplication...

**Comment by cbeust** [comment]
Done.

-- 
Cédric


On Thu, Jul 21, 2016 at 11:38 AM, Dmitry Zhuravlev <notifications@github.com

**Comment by derkork** [comment]
Thank you very much :+1:
