### ISSUE TITLE
Kobalt not finding dependencies of Kobalt-made artifact.

### ISSUE THREAD

**Issue by kyonifer** [cbeust/kobalt#283]
Artifact I'm trying to depend on is [here](https://bintray.com/kyonifer/maven/golem-backend-ejml#files/golem/golem-backend-ejml/0.6). I made an example project trying to use this artifact [here](https://github.com/kyonifer/golem/tree/trash). 

Running ./kobaltw run works fine with that repo because i explicitly depend on all the things golem-* does. However, if you remove the extra transitive deps as indicated by the comments in the build file, it fails to download or include the trans deps when building or running. A similar build.gradle test project is able to pull in golem-* without any extra deps specified, so it might be that I'm missing some meta-data somewhere that kobalt is looking for it. The [pom in bintray](https://bintray.com/kyonifer/maven/download_file?file_path=golem%2Fgolem-backend-ejml%2F0.6%2Fgolem-backend-ejml-0.6.pom)  has the deps listed.

**Comment by kyonifer** [comment]
Made a branch with the equivalent example project using gradle [here](https://github.com/kyonifer/golem/tree/trash_gradle). Looks like gradle brings in the deps listed in the pom onto the runtime classpath.

**Comment by cbeust** [comment]
Fixed in 0.869.
