### ISSUE TITLE
Make Kobalt easily usable as a deployed static version in the filesystem

### ISSUE THREAD

**Issue by kyonifer** [cbeust/kobalt#292]
The wrapper is a useful workflow, but sometimes its more convenient to use a static system-wide version that can be depended on (for example, if packages are in a versioned package manager and want to share a single copy of kobalt without redownloaded it for every project). It would therefore be desireable to support deploying /usr/bin/kobalt as something that can be invoked against a statically installed version of the kobalt jar.

Currently, if I try to run a standalone copy of kobalt thats not in my project directory, it will look to install things in ~/.kobalt. For example, unzipping the jar and running 

```
cd myproj
java -jar ~/Downloads/kobalt-0.867/kobalt/wrapper/kobalt-wrapper.jar
```

Downloads a copy of kobalt to ~/.kobalt instead of just using the one sitting next to it. Trying to manually use the versioned jar leads to
```
java -jar ~/Downloads/kobalt-0.867/kobalt/wrapper/kobalt-0.867.jar 

(snip)

Couldn't find /home/kyonifer/.kobalt/wrapper/dist/kobalt-0.867/kobalt/wrapper/kobalt-0.867.jar, using
  /home/kyonifer/kotlin/kobalt/kobaltBuild/classes /home/kyonifer/kotlin/kobalt/modules/kobalt-plugin-api/kobaltBuild/classes /home/kyonifer/kotlin/kobalt/modules/wrapper/kobaltBuild/classes /home/kyonifer/.kobalt/wrapper/dist/kobalt-0.866/kobalt/wrapper/kobalt-0.866.jar
*****
***** ERROR Invalid classpath: couldn't find /home/kyonifer/kotlin/kobalt/kobaltBuild/classes
*****
BUILD FAILED: 1
```

**Comment by cbeust** [comment]
I'm not following what you're trying to do. The distributions get downloaded in `~/.kobalt` so they can be shared across projects, isn't that what you'd call a "statically installed version of the kobalt jar"?

**Comment by kyonifer** [comment]
On linux, typically the system package manager controls system-wide directories like `/etc` and `/usr`, whereas the user controls directories such at `$HOME` and `/usr/local` (the latter being reserved for manually built packages). For example, Arch [prohibits packages from installing things directly to a home dir](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Directories).

Having a install in a system dir has some advantages, namely the install will be available to multiple users and survives a config wipe by a user. So I definitely think Kobalt should support system installs. Gradle, sbt, maven, et. al. all install to /usr/bin on Debian, Ubuntu, Arch...

The easiest path forward here might be to just install the wrapper to the system directories and have it at runtime grab the versioned jar to the ~/.kobalt cache (which is what im doing atm with the arch package). Thats not ideal because it would mean one kobalt jar downloaded per user, but it would allow packages to depend on mine. In addition that gives up the most useful feature of the wrapper in my mind, which is the ability to set a version in kobalt-wrapper.properties and have the wrapper use it (because users shouldnt be modifying files in the system, and afaik kobalt-wrapper.properties has to be sitting next to the wrapper.jar). Perhaps make a way to have the wrapper look for kobalt-wrapper.properties in ~/.kobalt if it exists?

**Comment by cbeust** [comment]
This is the kind of OS-specific feature I'd rather leave out of Kobalt and up to package managers and installers.

For what it's worth, Gradle has been operating with that same wrapper system for 8+ years, so I think this approach works reasonably well.

**Comment by kyonifer** [comment]
I agree that Gradle's wrapper system works quite well. Unfortunately Kobalt isn't matching their capabilities, which is what I'm noting here. Taking gradle as an example, it installs a shell script to /usr/bin/gradle, which after setting up the env vars runs `java ... -classpath "/usr/share/java/gradle/lib/gradle-launcher-2.14.jar" "$@"`, which is a statically installed jar in the system path /usr/share/java. At no point is a jar downloaded at runtime or a jar copied into ~/.gradle. Multi-user setups all reference the same jars installed in /usr/share/java/gradle. In short, gradle supports site-wide deployment, but Kobalt doesnt. Im not sure I see how supporting running in a folder different than ~/.kobalt is OS specific.

**Comment by drmoose** [comment]
The KOBALT_JAR environment variable seems to do what you want.

```
export KOBALT_JAR="$(readlink -f ~/Downloads/kobalt-0.867/kobalt/wrapper/kobalt-0.867.jar)"
java -jar "$KOBALT_JAR"
```

**Comment by kyonifer** [comment]
Indeed, that looks like exactly the config option I was proposing, good catch. @cbeust might be worth adding to the docs that this is the route to go to run standalone.

**Comment by cbeust** [comment]
`KOBALT_JAR` is kind of an internal environment variable I use for development, hence why it's not documented :-)

**Comment by kyonifer** [comment]
fair enough... is that something that might disappear then? it'd be super helpful for packaging on linux if theres a permanent way to run the kobalt jar when its sitting in /usr/local.

**Comment by cbeust** [comment]
No, it's vital to development so it's probably going to stay.
