### ISSUE TITLE
Move OS and JVM related code to a common package

### ISSUE THREAD

**Issue by benignbala** [cbeust/kobalt#3]
Since kobalt is planning to be a generic build tool in the Java/JVM ecosystem, the OperatingSystem.kt and JvmInfo.kt files should be in a common package accessible to all plugins that need the JVM. For eg. if I have to add support to Groovy/Scala, I could easily reuse those as needed.

**Comment by cbeust** [comment]
Good point.

**Comment by benignbala** [comment]
Shall I have a try at this ?

**Comment by cbeust** [comment]
Go ahead.

Right now, let's move them to `com.beust.kobalt`.

I'm not quite settled yet on where to put public stuff and how to organize it, right now it's tentatively `com.beust.kobalt` and `com.beust.kobalt.api`, although the boundary between both is not yet clear in my mind.

**Comment by benignbala** [comment]
Since this will anyway be accessed only by various plugins, how about moving them to <code>com.beust.kobalt.plugin</code> package ?

**Comment by cbeust** [comment]
Potentially anything in the public API can be accessed by the plug-ins, so
let's keep it simple and limit this public API to just two packages for
now: com.beust.kobalt and com.beust.kobalt.api.

-- 
Cédric

**Comment by benignbala** [comment]
Agreed. I'll move it to <code>com.beust.kobalt</code>

**Comment by benignbala** [comment]
I guess we can mark this closed. The   PR has already been pulled in. If we decide to re-organise the code again, we can have separate tickets/PRs again. Thanks
