### ISSUE TITLE
Fails to build complex dependencies from Maven

### ISSUE THREAD

**Issue by jkbbwr** [cbeust/kobalt#30]
When compiling dependencies from Maven that use JNI it seems to break pathing and cause issues.

This causes JFFI to not find its native library, or for the ClassLoader not to find JFFI

Build.kt

```
import com.beust.kobalt.*
import com.beust.kobalt.plugin.packaging.assemble
import com.beust.kobalt.plugin.kotlin.*

val repos = repos()

val p = kotlinProject {

    name = "c"
    group = "c"
    artifactId = name
    version = "0.1"

    sourceDirectories {
        path("src")
    }

    dependencies {
        compile(file("lib/kotlin-runtime.jar"))
        compile(file("lib/kotlin-reflect.jar"))
        compile("org.abstractj.kalium:kalium:0.4.0")
    }

    assemble {
        jar {
            fatJar = true
            manifest {
                attributes("Main-Class", "path")
            }
        }
    }
}
```

Simple testing script 

```
package c

import org.abstractj.kalium.keys.SigningKey

fun main(args: Array<String>) {
    val sk = SigningKey()
    println(sk)
}
```

**Comment by cbeust** [comment]
Is this project available on github with a working gradle or pom build (with its native library)? It would help if I can start from a project that builds fine in order to investigate what's missing on the kobalt side.

Thanks!

**Comment by jkbbwr** [comment]
Its only that source file.  I can stage you a simple project on github if
you desire

**Comment by cy6erGn0m** [comment]
The requires *.so files are in the jffi-native.jar. It looks like kobalt doesn't support dependencies with classifiers, isn't it ? cc @cbeust

**Comment by cbeust** [comment]
Correct, classifiers are not supported yet. Packages are, though (e.g. `com.android:x:aar:1.0`).

Do you have an example of a github repo that builds with gradle and has native libraries in it?
