### ISSUE TITLE
Give more accurate version info in `DependencyData` for the IDEA plug-in

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt#320]
When the IDEA plug-in calls the Kobalt server and asks for dependencies, these are returned in the form a graph, and this graph can contain the same artifact with different versions:
```
com.squareup.retrofit2:converter-gson:jar:2.1.0
    com.squareup.retrofit2:retrofit:jar:2.1.0
        com.squareup.okhttp3:okhttp:jar:3.3.0
            com.squareup.okio:okio:jar:1.8.0   <-------------
com.squareup.okhttp3:logging-interceptor:jar:3.2.0
    com.squareup.okhttp3:okhttp:jar:3.2.0
        com.squareup.okio:okio:jar:1.6.0 <------------
```

This is useful in order to display the correct tree in the IDEA Kobalt window, but it's dangerous when used to set up the dependencies because you end up with possibly conflicting versions:

![image](https://cloud.githubusercontent.com/assets/92322/22534609/f61b96c8-e8a9-11e6-9c68-eaf8cc20e88a.png)

In order to fix that, I am going to add a boolean `isLatest` to the `DependencyData` class. When the IDEA plug-in is setting up the dependencies and walks this dependency graph, it should only keep the `DependencyData` instances that have `isLatest` to `true`.

@dmitry-zhuravlev, what do you think?

**Comment by cbeust** [comment]
This is implemented in `HEAD` but not released yet.

@dmitry-zhuravlev: To test, just build Kobalt, launch `./kobaltw --server --force` and then Sync from IDEA. The response you receive from the server when you sync should have `DependencyData` JSON objects that have an additional `isLatest` boolean attribute.

**Comment by dmitry-zhuravlev** [comment]
Yeach, sounds good for the first time. However Gradle have more flexible way to manage such conflicts (see [Component selection rules)](https://docs.gradle.org/current/userguide/dependency_management.html#component_selection_rules)

Also Maven integration in IDEA have a good highlights for such conflicts:
![image](https://cloud.githubusercontent.com/assets/6297697/22548244/9b79b47c-e956-11e6-81f8-dc532fdd0876.png)

But at the moment lets keep it simple and use the `isLatest`. I'll reckeck and probably add a filter by `isLatest==true` into dependency tree.

**Comment by cbeust** [comment]
`Aether` has a similar thing called `DependencyFilter`, which I use quite a bit inside Kobalt. However, it seems to me this approach is limited since such filters need to know the entire tree of dependencies before they can decide whether to accept or reject a specific dependency.

Looking forward to trying the plug-in once you've implemented the IDEA part!

**Comment by dmitry-zhuravlev** [comment]
Implemented here https://github.com/cbeust/kobalt-intellij-plugin/commit/4bcaaa87f3e4d90604b408ae96e17fd2eae26f56 
You can give a try ;)

**Comment by cbeust** [comment]
Great!

It's working, however the plug-in **needs** to be talking to the latest version of Kobalt. If it connects to an older version, it receives zero dependencies. This is weird since you defined the default value to `true`:

```
data class DependencyData(val id: String, val scope: String, val path: String, var isLatest: Boolean = true,
```

I am guessing the JSON deserialization overrides that default value to `false` if that flag is not specified in the JSON, regardless of the Kotlin default value. Is this something you can fix on your end?

**Comment by cbeust** [comment]
On a separate note: I have been trying to debug/confirm this myself by putting a break point in `KobaltProjectResolver:121`, however that break point was never hit.

I remember you telling me that these plug-ins are launched in a separate thread or JVM?

Is there a way I can force it to be in process?

Or more generally: how do I get this break point to work?

Thanks!

**Comment by dmitry-zhuravlev** [comment]
> It's working, however the plug-in needs to be talking to the latest version of Kobalt. If it connects to an older version, it receives zero dependencies.

I think it is a part of general concept of interoperability between plugin version and Kobalt version. Each version of plugin should be restricted to the particular version range of Kobalt. But this is a part of another feature.
In this particular case it could be set like nullable field, hope JSON deserialization will preserve the null-fields....

> On a separate note: I have been trying to debug/confirm this myself by putting a break point in KobaltProjectResolver:121, however that break point was never hit.

Yes, it is a separate process. To debug it you can specify in `KobaltManager` `parameters.vmParametersList.addProperty(...)` the corresponding JVM remote debug options.

**Comment by cbeust** [comment]
And what are these options? It's pretty hard to find any documentation about this, the best I could find is:

https://www.jetbrains.com/help/idea/2016.3/running-and-debugging-plugins.html

but this page makes no mention of running plug-ins in the same process...

**Comment by dmitry-zhuravlev** [comment]
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005`
You can find it in Run/Debug Configurations -> Remote

**Comment by cbeust** [comment]
Right, but I can't get this to work.

First of all, even if I specify the remote options explicitly before launching the plug-in:

Inline image 1
![image](https://cloud.githubusercontent.com/assets/92322/22753992/dc43bc78-edf2-11e6-8e33-b138560c30c0.png)

It looks like IDEA overrides them and launches the plug-in with its own coordinates:

```
$ ps aux|grep java|grep address=
cedricbeust      76095   0.0  5.7  6677240 951600   ??  S    11:31AM   1:09.67 /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:62434,suspend=y,server=n -Xmx512m -Xms256m -XX:MaxPermSize=250m -ea -Xbootclasspath/a:/Applications/IntelliJ IDEA.app/Contents/lib/boot.jar -Didea.config.path=/Users/cedricbeust/Library/Caches/IntelliJIdea2016.2/plugins-sandbox/config -Didea.system.path=/Users/cedricbeust/Library/Caches/IntelliJIdea2016.2/plugins-sandbox/system -Didea.plugins.path=/Users/cedricbeust/Library/Caches/IntelliJIdea2016.2/plugins-sandbox/plugins -Didea.classpath.index.enabled=false -Didea.required.plugins.id=com.beust.kobalt.intellij -Didea.smooth.progress=false -Dapple.laf.useScreenMenuBar=true -Dapple.awt.fileDialogForDirectories=true -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/lib/tools.jar:/Applications/IntelliJ IDEA.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/openapi.jar:/Applications/IntelliJ IDEA.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea.jar com.intellij.idea.Main
```

Ok, not a big deal, I'll just use 62434 as shown in the `ps` above. So I create a remote debug launch configuration that connects to that port, but it fails:

Inline image 2
![image](https://cloud.githubusercontent.com/assets/92322/22753952/beed43d8-edf2-11e6-9be1-09dc2274c621.png)

Any idea what I'm doing wrong?

**Comment by dmitry-zhuravlev** [comment]
Hm... Image 1 show that you pass the VM parameters to the JVM which start new IDEA instance. It is not what we want :)
Try the following:
1) Create Remote debug configuration. E.g.
![image](https://cloud.githubusercontent.com/assets/6297697/22778022/54c46d36-eec6-11e6-8898-ee070d518791.png)
2) Put in `KobaltManager.enhanceRemoteProcessing` method the following line: `parameters.vmParametersList.addParametersString("-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5009")`  Pay attention that it should be `suspend=y` instead of `suspend=n` - this will force to JVM to stop execution and wait for our remote debug connection.
3) Start Kobalt plug-in configuration. (and replace VM options specified on image 1 by `-Xmx512m -Xms256m -XX:MaxPermSize=250m -ea`)
4) Within started IDEA instance press on "Refresh Kobalt projects" button. This will trigger the dependency resolutution.
5) Run remote debug configuration (`Debug Kobalt Resolve Execution`)

**Comment by cbeust** [comment]
Thanks, I was finally able to debug the plug-in!

And I figured out what's going on.

First of all, here is the stack trace that I was so desperately trying to find:

```
java.lang.IncompatibleClassChangeError: org/eclipse/jetty/websocket/servlet/ServletUpgradeRequest
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:168)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:207)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

And this confirmed my suspicion: it's not a kotlinc/kobalt issue, it looks more like a typical bytecode problem. So I dug up further in the bowels of the websocket library and I found out that there were two (apparently incompatible) different versions of the same `websocket-server` library.

I removed one of these and everything is working again.

I just deployed 0.923 with this fix: try it and you should see that the plug-in can sync with it without any issue (can you test it from a 1.0.6 IDEA plug-in too? I haven't tested that but it should work as well).
