### ISSUE TITLE
convenience feature idea: add a dependency from the command line

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#322]
In the spirit of php's [composer](https://getcomposer.org/) and go's [glide](https://github.com/Masterminds/glide), it would be cool if this were possible with Kobalt:

```./kobaltw dep com.sparkjava:spark-core:2.5.4 ```

If there is only one project module in the Build.kt, the dependency would automatically be added to the project's compile dependencies

If there are multiple projects, it would be cool if Kobalt asked which one to add to.  Or an error could be thrown.

it might also be cool to support adding of repos.  this would make it easy to copy/paste from the web and get started trying some library.

```./kobaltw repo https://xyz.com/repo```

**Comment by cbeust** [comment]
Mmm... I'm a bit torn about these since there are ways in which you can create a build file that's still not exactly what you want (e.g. which module to add, like you said, or which kind of dependency it is, etc...).

The advantage, though, is that you can guarantee that these are being added with the right syntax (e.g. recently I introduced `buildScript`).

**Comment by pabl0rg** [comment]
I guess it wouldn't be ideal to have to parse and edit the build.kt. Maybe these dependencies could go in a yaml file that the build reads.  

In that case it wouldn't even have to be a feature baked into kobalt.

**Comment by ethauvin** [comment]
You can actually do it using the `-D` flag that I added in [2d6c8f7](https://github.com/cbeust/kobalt/commit/2d6c8f720cb27421f68c5b3a829d2438fe001c4c)

`./kobaltw -Dspark.dep=com.sparkjava:spark-core:2.5.4`

and then in `Build.kt`:

```
dependencies {
    complile(System.getProperty("spark.dep", "com.sparkjava:spark-core:"))
}
```

I haven't actually tried it, but it should work.

**Comment by cbeust** [comment]
Indeed it should work.

**Comment by pabl0rg** [comment]
@ethauvin That's a cool use of Kobalt + Kotlin + JVM but not exactly what I had in mind.  Anyway, what I had in mind could be done in a plugin...
