### ISSUE TITLE
Change kobalt.FindKobaltProject keyboard shortcut from Shift+K

### ISSUE THREAD

**Issue by CrazyCoder** [cbeust/kobalt#333]
Shift+K is a poor choice and will block typing capital `K` in the editor. Please consider changing the default mapping.

**Comment by cbeust** [comment]
Yes, it's done in the latest version of the plug-in, which we haven't published yet.

I'm attaching it here if you want to install it locally
[kobalt-intellij-plugin.zip](https://github.com/cbeust/kobalt/files/805247/kobalt-intellij-plugin.zip)
