### ISSUE TITLE
Proper CI for Linux / macOS / Windows

### ISSUE THREAD

**Issue by sschuberth** [cbeust/kobalt#338]
The current "build failing" badge at the top of the README is not very encouraging when thinking about contributing to the project. Please ensure a properly working CI so PRs can be automatically checked at least against compile errors on the various platforms. If desired, I can assist with this.

**Comment by pawegio** [comment]
AFAIK kobalt moved to TeamCity, but I agree that this badge with failing status from travis does not encourage to contribute.

**Comment by cbeust** [comment]
Indeed. Kobalt is now built on TeamCity (because Travis was aborting for mysterious reasons). I'll fix the badge.

**Comment by cbeust** [comment]
Github doesn't seem to support TeamCity at the moment so I'm removing the badge for now.

**Comment by sschuberth** [comment]
I'd just like to emphasize that it's not about GitHub to support TeamCity, but about TeamCity to provide a GitHub integration. And from spending a few seconds on a Google search it looks like there are many [ways](https://blog.jetbrains.com/teamcity/2013/02/automatically-building-pull-requests-from-github-with-teamcity/) [to](https://github.com/jonnyzzz/TeamCity.GitHub) [do](https://github.com/JetBrains/commit-status-publisher) [that](http://blog.petegoo.com/2015/03/14/teamcity-github/) already.

**Comment by cbeust** [comment]
Thanks, I'll look into it!


-- 
Cédric

**Comment by cbeust** [comment]
@sschuberth It looks like all these solutions assume you're running your own TeamCity server.

Kobalt is being built on JetBrains' own TeamCity server so I don't have much control over this. Maybe they have some Github integration plug-ins installed, need to look into it.

**Comment by sschuberth** [comment]
@cbeust JetBrains' own [commit-status-publisher](https://github.com/JetBrains/commit-status-publisher) says it's bundled since TeamCity 10.x, so if you're running at least that version nothing needs to be installed. I guess you should simply look whether the build feature is available to you.

**Comment by cbeust** [comment]
I turned on the commit status publisher and it's working fine for individual commits but not quite well for the README badge, take a look at the home page.

The URL is:

 https://teamcity.jetbrains.com/app/rest/builds/buildType:(id:OpenSourceProjects_Kobalt_Build)/statusIcon

If I load it from my browser, I get the green badge but as you can see, from the `README.md`, there's an authorization problem...

**Comment by cbeust** [comment]
Never mind, I figured it out:

![image](https://cloud.githubusercontent.com/assets/92322/23973654/52a43566-0994-11e7-8f22-f499dd3e458e.png)

**Comment by sschuberth** [comment]
It's *looking* good, but clicking the badge just shows the badge image. Would it be possible to make the badge link to the actual build log?

**Comment by cbeust** [comment]
Done.

**Comment by sschuberth** [comment]
Thanks, we're getting closer :-) Now is there a way for anonymous user to at least *see* the log?

**Comment by cbeust** [comment]
It should be public now.
