### ISSUE TITLE
Upload to Bintray generates warning about duplicate tag

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#341]
```
***** WARNING tag 'Tag={
object 8ed92e818c7d44791a0a40e483ddc168cb53e72e
type commit
tag 0.5.2
tagger PersonIdent[Erik C. Thauvin, erik@thauvin.net, Wed Mar 8 11:47:21 2017 -0800]

}' already exists
```

**Comment by ethauvin** [comment]
@cbeust If you're going to look at the Bintray API for changes, see if they have a way to set a description for the release. That would be nice to be able to set it in Kobalt.

**Comment by cbeust** [comment]
They would have to change for every upload, though, correct? Are you thinking about something like

```
bintray {
  description = "Fix bugs"
}
```

and modifying this string each time before uploading?

**Comment by ethauvin** [comment]
Yeah, but most people would just use something like:

```
bintray {
   description = "$name $version"
}
```
or the such. On the Bintray website, the description looks more like a title to me.

**Comment by cbeust** [comment]
I don’t see any description for individual version uploads, even on the web site:  https://bintray.com/cbeust/maven/klaxon/0.30

**Comment by cbeust** [comment]
That's Kobalt attempting to tag your git repo with the project version. Obviously, this will fail if you make multiple uploads without bumping your project version
