### ISSUE TITLE
Improve handling of profiles

### ISSUE THREAD

**Issue by dittert** [cbeust/kobalt#353]
The current implementation of ```--profiles``` has the limitation that Kobalt can't know if it's necessary to recompile ```Build.kt``` when the value of a profile changes.

I'd like to suggest to use a delegate that determines the value at runtime:

```val experimental: Boolean by profile()```

As profiles currently are only boolean values, one could even omit the type of the variable.

The command line would not change:

```./kobaltw --profiles experimental assemble```

See discussion here: https://kotlinlang.slack.com/archives/C0BRKJ9K9/p1490455683178877

**Comment by cbeust** [comment]
Done.
