### ISSUE TITLE
application{} executing fails if jar{} name has been changed.

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#355]
```
    name = "example"
    version = 0.1

    assemble {
        jar {
            name = "${project.name}.jar"
            fatJar = true
            manifest {
                attributes("Main-Class", mainClassName)
            }
        }
    }

    application {
        mainClass = mainClassName
        args("-v")
    }
```

`application` will try to execute `java.exe -classpath .\kobaltBuild\libs\example-0.1.jar` which does not exists.

Additionally, since `fatJar = true`, the `classpath` should not include all the dependencies like it does now.

**Comment by ethauvin** [comment]
As discussed on Slack, if `fatJar = true`, anything included in `apt()` should be excluded from the jar.

**Comment by ethauvin** [comment]
@cbeust What say you on that one?

Looking at the code, changing the jar name in the project's properties would wreck havoc.

Would it be best handled with a `jarName` parameter in the `application` directive?

**Comment by cbeust** [comment]
Looks pretty straightforward: `application` should use the name from `jar`, not one it made up.
