### ISSUE TITLE
install{} should have include() directive 

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#359]
```
    install {
        libDir = "deploy"
        include(from("logs"), to("logs"), glob("**/*"))
    }
```
This will make deployment a lot easier.

'libDir` should probably be renamed too.

@cbeust suggested renaming `libDir` to `target` or `destination` (https://github.com/cbeust/version-processor/issues/2#issuecomment-289293406)

**Comment by cbeust** [comment]
Fixed in 1.0.50. The new syntax is:

```
    install {
        collect(compileDependencies).map {
            copy(it, to("deploy"))
        }
    }
```
