### ISSUE TITLE
kobalt's Build.kt file appears to be included in all builds

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#360]
[example.zip](https://github.com/cbeust/kobalt/files/870938/example.zip)

Added:
```
object Versions {
    val aether = "6.10"
}
```

using `println("${Versions.aether}")` returns `1.0.2.v20150114` as defined in the Kobalt's own build file, and not `6.10` as expected.

**Comment by cbeust** [comment]
Not sure how that `Versions.class` got included but I added a check against it.

Should be fixed in the latest (1.0.29).
