### ISSUE TITLE
Add `--resolveJavadoc` and `--resolveSources` for Kobalt server

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt#372]
[Suggestion from @dmitry-zhuravlev](https://github.com/cbeust/kobalt-intellij-plugin/issues/54#issuecomment-290458957):

So it would be good to have --resolveSources --resolveJavadoc parameters in Kobalt server. If the server receive --resolveSources then it should download all sources for all dependencies mentioned in Build.kt.
The same things should be happen with --resolveJavadoc parameter but for javadocs.

**Comment by dmitry-zhuravlev** [comment]
Oh, I forgot to mention that this should be not parameters to startup the server but parameters for `/v1/getDependencyGraph` endpoint (like profiles). This is because the Kobalt server instance could be shared between different builds and hence this parameters is build dependant.

**Comment by cbeust** [comment]
Fair point but I'm not sure there is much harm in deciding that all downloads from a specific server will download sources and javadocs.

I mean, when wouldn't a server launched by the IDEA plug-in **not** want that?

**Comment by cbeust** [comment]
By the way, you can already do this today to download sources:

```
./kobaltw --resolve org.testng:testng:jar:sources:6.11
```

@dmitry-zhuravlev Maybe the plug-in could simply use this so I don't have anything to add to Kobalt?

**Comment by dmitry-zhuravlev** [comment]
>Fair point but I'm not sure there is much harm in deciding that all downloads from a specific server will download sources and javadocs

Just a simple use case: when an user opened two IDEA projects in (separated windows) the only one Kobalt server started. First project could be configured to download sources but the second project can be configured not to download any sources/javadocs. So when IDEA plugin request dependencies from the Kobalt server it also request the way to download (or not) sources for dependencies specified in Build.kt. Also note that before plugin request server for dependencies it simple doesn't know anything about dependencies, so it cannot call --resolve <dependency_id> directly. Also it could be a hundred dependencies (with transitive ones) in Build.kt so it shouldn't call --resolve for them all ;) The main idea here is to trigger Aether to download also artifacts with classifiers "sources", "javadoc", and this behavior should be controlled by two boolean flags "sources=true", "javadoc=true". This flags will be sended by IDEA plugin to Kobalt server.

**Comment by cbeust** [comment]
Point taken about `--resolve` not being good enough here.

But I still think a command line switch `--downloadSources` is good enough. The server is typically started by tools (e.g. IDEA) that will need these sources anyway. I'll start with that and later, we can decide if it's worth it to move these flags into the `getDependencyGraph()` API call.

**Comment by dmitry-zhuravlev** [comment]
> will need these sources anyway

It fully depends on project. E.g. in one project I want to download all dependencies, in another I don't want to download it. So if I firstly open the project and start the server with "--downloadSources" flag the same flag will be automatically reused for the second opened project (just because it could be only one running server instance at the same time). So it is wrong....

**Comment by cbeust** [comment]
I don't see when or how you would decide that you don't want to download sources, can you elaborate?

Anyway, I just implemented `--downloadSources` (this will download both sources and javadoc), you can start playing with this and we can continue the discussion about whether this belongs in the API.

The downside of this approach is that all the transitive dependencies sources are being downloaded, which might be overkill. Eventually, we want to download no sources and wait until the user clicks the "Download sources" for a specific file.

**Comment by cbeust** [comment]
By the way, the ideal case I described above ("Don't download any sources and wait for the user to request a specific source") is one that is solved by invoke `./kobaltw --resolve x:y:sources:jar:v`, so that might still come in handy for you if you figure out how to make the "Download sources" button.

**Comment by dmitry-zhuravlev** [comment]
>I don't see when or how you would decide that you don't want to download sources, can you elaborate?

Via checkbox:
![image](https://cloud.githubusercontent.com/assets/6297697/24553272/65bfe17c-1632-11e7-8a9b-faa0244ea218.png)
 
To make it properly work see this: https://github.com/cbeust/kobalt/pull/374

Also I rechecked in general `--downloadSources` functionality and it seems that it don't download the needed sources and javadoc. Also server sends sources\javadoc like a regular dependencies to plugin:
![image](https://cloud.githubusercontent.com/assets/6297697/24553439/f1c79a20-1632-11e7-8452-4f5c48cb6cda.png)

So it should be fixed somehow....

**Comment by cbeust** [comment]
I meant that I don't see why a user would decide they don't want to download the sources.

Anyway, I'll look into the issues you mentioned and I'll get back to you.

**Comment by dmitry-zhuravlev** [comment]
> I meant that I don't see why a user would decide they don't want to download the sources.

Just belive me, internet connection could be veeeeery slow. E.g. I always strugled with this problem in some places :-(

**Comment by dmitry-zhuravlev** [comment]
Just fixed javadoc/sources resolution. See https://github.com/cbeust/kobalt/pull/374/commits/b9a3a4f40b426544bddbee4715e9696a09ec0cab
However there is still problem:
It seems that artifact resolution work only in case if there is no artifact present. E.g. if I have `{HOME}/.kobalt/cache/org/jetbrains/kotlin/kotlin-stdlib/1.1.1` artifact then no resolution of source/javadoc take place. If I manually delete `1.1.1` folder then Aether will download all needed jars.
@cbeust Maybe you know how to force resolution for artifacts?

**Comment by cbeust** [comment]
> Just believe me, internet connection could be veeeeery slow. E.g. I always strugled with this problem in some places :-(

I totally agree, which is why I think that making a blanket "download sources" at the resolution level is wrong since it will download the source/javadoc for not just one dependency but the whole graph.

The right time to download the sources is not when you call `getDependencyGraph()` but when the user explicitly requests it by pressing on the "Download source" of a specific file.

What do you think?

**Comment by cbeust** [comment]
> It seems that artifact resolution work only in case if there is no artifact present. E.g. if I have {HOME}/.kobalt/cache/org/jetbrains/kotlin/kotlin-stdlib/1.1.1 artifact then no resolution of source/javadoc take place. If I manually delete 1.1.1 folder then Aether will download all needed jars.

Mmh I can't reproduce this:

```
$ ls ~/.kobalt/cache/org/testng/testng/6.10
_remote.repositories		testng-6.10-javadoc.jar.sha1	testng-6.10.jar.sha1		testng-6.10.pom.sha1
testng-6.10-javadoc.jar		testng-6.10.jar			testng-6.10.pom

$`down': k --downloadSources --resolve org.testng:testng:6.10
  Regular compilation time: 1817 ms
Downloaded artifact org.testng:testng:jar:sources:6.10 from  (https://jcenter.bintray.com/, default, releases+snapshots)

$ ls ~/.kobalt/cache/org/testng/testng/6.10
_remote.repositories		testng-6.10-javadoc.jar.sha1	testng-6.10-sources.jar.sha1	testng-6.10.jar.sha1		testng-6.10.pom.sha1
testng-6.10-javadoc.jar		testng-6.10-sources.jar		testng-6.10.jar			testng-6.10.pom

```

**Comment by dmitry-zhuravlev** [comment]
>Mmh I can't reproduce this:

Probably you already have sources/javadoc resolved for `testng` dependency. Try to do so on dependency without sources/javadoc presented.

**Comment by cbeust** [comment]
> It seems that the following check in AetherDependency.kt create the mentioned problem:

Ah good catch, I was using a different code path with my attempt to reproduce. Looking into it.

**Comment by cbeust** [comment]
@dmitry-zhuravlev Fixed in 1.0.43 with https://github.com/cbeust/kobalt/commit/bfa2fb072e585d98ac11b4abe67875223da23334

This bug is a leftover of when I was using my own resolver. With Maven Resolver, I don't need to check this any more.

**Comment by dmitry-zhuravlev** [comment]
Finally got it works! Please see the last changes in PR: https://github.com/cbeust/kobalt/pull/374/files
The main idea was to shift javadoc/sources resolution to:
`AetherDependency.jarFile get()`. 
Because `jarFile` property is <b>always</b> to be called. 

The main problem in the previous implementations was if-else branch in `AetherDependency.jarFile get()`
E.g. in case if user already have binary jar e.g. `testng-6.9.11.jar` present but don't have `testng-6.9.11-javadoc.jar`, `testng-6.9.11-sources.jar` -  the resolution of javadoc/sources will not take place because `artifact.file != null` will `true`   (`artifact.file` is always pointed to `testng-6.9.11.jar`).

Also for now the resolution of sources/javadoc is becomes fully independent from the regular jar dependency resolution- so if it fails it will not affect resolution of the regular jar dependency.

**Comment by dmitry-zhuravlev** [comment]
Together with an option in IDEA plugin:
![image](https://cloud.githubusercontent.com/assets/6297697/24605710/96fdf548-1872-11e7-9aeb-953c696ff4c0.png)
This feature is extremelly usefull: E.g. user could enable source resolution via plugin, syncronize the project only once and get all sources for all dependencies. After that user can disable source resolutions but sources/javadocs will be already there in `.kobalt\cache` ;-)
