### ISSUE TITLE
Mismatch between method signatures in HostConfig between kobalt-plugin-api and kobalt causes java.lang.NoSuchMethodError.

### ISSUE THREAD

**Issue by rhencke** [cbeust/kobalt#389]
In the current version of kobalt-plugin-api, the HostConfig class is seen as having the following constructor signature.
```
data class HostConfig(var url: String = "", var username: String? = null, var password: String? = null) {
```

In the latest version of Kobalt, HostConfig gained a parameter:

```
data class HostConfig(var url: String = "", var name: String = url, var username: String? = null,
        var password: String? = null) {
```

Unfortunately, this means that plugins that call the HostConfig constructor, using the current version of kobalt-plugin-api, are incompatible with the latest version of Kobalt - attempting to load a plugin that calls HostConfig's constructor results in the following error (or one like it)

```
java.lang.NoSuchMethodError: com.beust.kobalt.HostConfig.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
        at com.github.rhencke.kobalt.jpi.JpiPlugin.reposFor(JpiPlugin.kt:40)
        at com.beust.kobalt.app.ProjectFinder.initForBuildFile(ProjectFinder.kt:33)
        at com.beust.kobalt.Options.run(Options.kt:49)
        at com.beust.kobalt.Main.runWithArgs(Main.kt:119)
        at com.beust.kobalt.Main.run(Main.kt:100)
        at com.beust.kobalt.MainKt.mainNoExit(Main.kt:42)
        at com.beust.kobalt.MainKt.main(Main.kt:20)
```

**Comment by cbeust** [comment]
How can I reproduce this?

**Comment by rhencke** [comment]
I'll pare what I have down to a minimal version and get you a small project that reproduces this tonight.  Thanks for looking at this.

**Comment by rhencke** [comment]
Please find a reproducible version at https://github.com/rhencke/issue389

You can run build.sh in that repository to reproduce the issue.

The 'plugin' project is a Kobalt plugin that makes a call to the HostConfig constructor.
The 'projectUsingPlugin' project attempts to use the above plugin, but throws java.lang.NoSuchMethodError trying to.

**Comment by cbeust** [comment]
Yes, the `kobalt-plugin-api` needed to be updated. I just uploaded `1.0.55`. Clean your project and try again. Kobalt should automatically download that version but somehow, this didn't happen for me, let me know if you see the same anomaly and file an issue if you do.

If this doesn't work, just specify the version directly for now:

```
    dependencies {
        compile("com.beust:kobalt-plugin-api:")
    }
```
