### ISSUE TITLE
'provided' dependencies are not resolvable at compile time

### ISSUE THREAD

**Issue by rhencke** [cbeust/kobalt#391]
If a Kobalt project marks a dependency as 'provided', as in the following (granted, nonsensical) example:

```kotlin
    dependencies {
        provided("org.hamcrest:hamcrest-core:1.3")
    }
```

the classes cannot be resolved at compile time.  This seems to be new behavior in 1.0.54.

To reproduce, here is a sample project:

https://github.com/rhencke/issue390

If you run 'build.sh', you will see the issue.

**Comment by rhencke** [comment]
Ah, I mis-guessed what the issue number was going to be.  The repo is for issue 391, not 390.

**Comment by cbeust** [comment]
1.0.58.
