### ISSUE TITLE
application always run from root directory

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#393]
```
val p = project {
 ...
}

val example = project(p) {
    name = "example"
    directory = "example"
    ...
    application {
        mainClass = "com.example.foo"
    }
}
```
`./kobaltw example:run` will execute from the root directory, not `directory`.

This will be even more important if Kobalt is to support multiple build files.

Probably related to #273

**Comment by cbeust** [comment]
A Java process can't change its current directory and `:run` is run with the current Kobalt process

Besides, I'd argue it's up to the user to pick which directory to run from.

**Comment by ethauvin** [comment]
There's gotta be a way, because Gradle does it. 

https://docs.gradle.org/current/userguide/multi_project_builds.html

In their case that even applies to compiling, etc. Every is done just like if you were building from the subproject directory.

**Comment by cbeust** [comment]
Yes, you just need to launch it in a separate process. I can modify `run` to do that.

**Comment by ethauvin** [comment]
But maybe it should apply to the entire build process (compiling, etc.), if a `directory` is specified, it should be the root.

**Comment by cbeust** [comment]
1.0.57.
