### ISSUE TITLE
Transient dependencies issues with collect()

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#395]
Assuming:

```
    dependencies {
        compile("org.apache.velocity:velocity:1.7")
    }
```

which resolves to:
```
╟ commons-collections:commons-collections:jar:3.2.1
╟ commons-lang:commons-lang:jar:2.4
╙ oro:oro:jar:2.0.8 (optional)
```

`collect(compileDependencies) ` will return `velocity`, `commons-collections` and `commons-lang` as expected.

Change to:

```
    dependencies {
        compile("org.apache.velocity:velocity:jar:1.7")
    }
```

`collect(compileDependencies)` will still return all three dependencies, not just `velocity`. I think that's a caching issue.

Additionally, I'm using an annotator, which requires both `apt(annotatorJar)` and `compile(annotatorJar)`, like most do.

The problem is when I'm using `collect(compileDependencies)`, I'm getting the annotator jar and it's dependencies, but I don't really need them to be deployed to the `install` target.

Gradle addresses that issue by providing a `compileOnly 'annotatorJar'` directive. Meaning that when collecting the compile dependencies, no annotator dependencies will be included.

**Comment by cbeust** [comment]
Working as expected. I resolved this resolution with [Maven Resolver's own example](https://github.com/apache/maven-resolver/blob/demo/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/ResolveTransitiveDependencies.java) and it produced the same result:

```
org.apache.velocity:velocity:jar:1.7 resolved to /Users/cedricbeust/java/maven-resolver/target/local-repo/org/apache/velocity/velocity/1.7/velocity-1.7.jar
commons-collections:commons-collections:jar:3.2.1 resolved to /Users/cedricbeust/java/maven-resolver/target/local-repo/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
commons-lang:commons-lang:jar:2.4 resolved to /Users/cedricbeust/java/maven-resolver/target/local-repo/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
oro:oro:jar:2.0.8 resolved to /Users/cedricbeust/java/maven-resolver/target/local-repo/oro/oro/2.0.8/oro-2.0.8.jar
```
