### ISSUE TITLE
Dep file, not File

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#398]
In https://github.com/cbeust/kobalt/blob/dca28669d1472a43c8aa11a6293b5cb1e217fc3a/modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/api/Project.kt#L131

```
class Dep(val File: File, val id: String)
```
should be:

```
class Dep(val file: File, val id: String)
```

**Comment by cbeust** [comment]
Fixed.
