### ISSUE TITLE
Running init on project without source fails

### ISSUE THREAD

**Issue by codeslubber** [cbeust/kobalt#40]
Refuses to make a build tool until there is at least one source file in the project.

Doesn't matter that much once you know. If this is by design maybe say in the message no source found.

**Comment by cbeust** [comment]
Indeed. I point this out in the [Ten Minute Tutorial](http://beust.com/kobalt/ten-minutes/index.html):

> I create an empty Main.kt in the example above so that calling ./kobaltw --init will detect the project as a Kotlin one. >I create an empty Main.kt in the example above so that calling ./kobaltw --init will detect the project as a Kotlin one. 

but I should point this out in the main documentation.

This limitation will eventually go away, I'll generate a generic Java build file if no sources can be found.

**Comment by codeslubber** [comment]
Ah, ok sorry for the noise. I looked at that but have made 3 projects since then...

**Comment by cbeust** [comment]
No worries, sorry for the trouble.
