### ISSUE TITLE
make kobaltw executable by default

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#401]
When Kobalt upgrades, it unzips the new version of the script to `~/.kobalt/wrapper/dist/kobalt-<version>/bin`

However, it is not executable (on mac at least).  Meaning that if I want to use that script to init a new project, I first have to make it executable.

```
>ls -l ~/.kobalt/wrapper/dist/kobalt-1.0.53/bin/
total 16
-rw-r--r--  1 jliska  staff  197 Apr  6 12:47 kobaltw
-rw-r--r--  1 jliska  staff  121 Apr  6 12:47 kobaltw.bat
```

**Comment by ethauvin** [comment]
Yes, I've noticed that too. I'll look into it, should be fixable.

**Comment by ethauvin** [comment]
@pabl0rg Do you have the same issue with the latest release?

**Comment by pabl0rg** [comment]
@ethauvin Yes.  

I guess this wouldn't be an issue if there is/was a better way to init Kobalt in a project .  The homebrew version wasn't working for me last time I tried (a long time ago) and either way, if I init with the homebrew version, I know I'll get an old kobalt and have to update.  So, I either install kobalt by running an existing project's kobaltw or dig around ~/.kobalt/wrapper/dist

```
ls -l ~/.kobalt/wrapper/dist/kobalt-1.0.59/bin/
total 16
-rw-r--r--  1 juanliska  staff  203 Apr 10 02:17 kobaltw
-rw-r--r--  1 juanliska  staff  125 Apr 10 02:17 kobaltw.bat
```

**Comment by ethauvin** [comment]
I don't get that at all on my Windows box:
```
$ ls -l ~/.kobalt/wrapper/dist/kobalt-1.0.59/bin/
total 2.0K
-rwxr-xr-x 1 erik 197609 203 Apr  9 11:29 kobaltw
-rw-r--r-- 1 erik 197609 125 Apr  9 11:29 kobaltw.bat
```
@cbeust will test on his Mac.

**Comment by ethauvin** [comment]
Actually, just saw the same on my Linux box. Will investigate some more.
