### ISSUE TITLE
Authenticated Maven Repositories

### ISSUE THREAD

**Issue by mhlz** [cbeust/kobalt#414]
I just tried converting a maven build to Kobalt, but I can't seem to get username and password authentication working.

I followed the instructions from [here](http://beust.com/kobalt/documentation/index.html#maven-repos-authenticated) but the build still fails to download the artifacts from jitpack.

Additionally, with the default log level this seems to result in an unhelpful NullPointerException and nothing else.

Is the local.properties still the current way to get authentication working?

**Comment by mhlz** [comment]
hm, I can't give out credentials for this project directly (I was hoping I was just overlooking something simple xD) but I'll try to see if I can get a MCVE of my issue up tomorrow.

**Comment by cbeust** [comment]
Maybe you can try to reproduce this on another Maven repo that requires authentication but with credentials you can share? (not sure if there's such a thing though)

**Comment by mhlz** [comment]
Okay, I set up an artifactory server with exactly one artifact in it that needs authentication.

The project can be found here: https://github.com/mhlz/kobalt-auth-example and I invited you as a collaborator (since I don't want that password being public since it's just the artifactory admin user).

I also included a maven build that works just fine, but using Kobalt the authentication doesn't seem to work.

**Comment by cbeust** [comment]
Great, I received the invitation, will take a look and get back to you.


-- 
Cédric

**Comment by cbeust** [comment]
I can't seem to authenticate with Maven, is something missing?

```
[ERROR] Failed to execute goal on project test: Could not resolve dependencies for project de.mhlz:test:jar:1.0-SNAPSHOT: Failed to collect dependencies at de.mhlz:playground:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for de.mhlz:playground:jar:1.0-SNAPSHOT: Could not transfer artifact de.mhlz:playground:pom:1.0-SNAPSHOT from/to arti (http://ilu.st:8081/artifactory/libs-snapshot): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

**Comment by mhlz** [comment]
You have to tell Maven to use the settings file:

    mvn -s settings.xml install

**Comment by cbeust** [comment]
That worked, thanks.

-- 
Cédric

**Comment by cbeust** [comment]
The code builds with Kobalt but it's not trying to resolve anything from that repo, do you have a dependency that can only be found there?

**Comment by mhlz** [comment]
The playground dependency from the Build.kt file is only on that server.

When I try to build with ./kobaltw test for example I only get a NullPointerException and with more verbose logging turned on I can see that it's trying to download the playground dependency but it's getting a 401

**Comment by cbeust** [comment]
Oh it's a test dependency, that's why I missed it, I see the failure now,
thanks


-- 
Cédric

**Comment by cbeust** [comment]
Fixed in 1.0.64, try this:

```
./kobaltw --update
./kobaltw test
```

**Comment by mhlz** [comment]
Yeah it's working now :) still some other issues with the bigger company project but I'll get those resolved I think. Thanks for your help and your quick fix :)

**Comment by cbeust** [comment]
Don't hesitate to ask if you run into more problems (either file an issue or come ask on Slack).
