### ISSUE TITLE
test tasks try run abstract class

### ISSUE THREAD

**Issue by debop** [cbeust/kobalt#417]
When define abstract class for Testing.
Kobalt try to run abstract test class, and failure ^^

**Comment by cbeust** [comment]
Can you be more specific? Do you have a project I can clone and build to reproduce the problem?

**Comment by debop** [comment]
Thanks ^^

https://github.com/debop/koda-time


At First, modify AbstractKodaTimesTest to abstract 

https://github.com/debop/koda-time/blob/develop/src/test/kotlin/com/github/debop/kodatimes/AbstractKodaTimesTest.kt

**Comment by cbeust** [comment]
I see the error.

Your instructions show how to build with Gradle, do you still have your Gradle build? Can you restore it so I can compare how Gradle handles abstract classes?

Thanks.

**Comment by debop** [comment]
You can see tag 1.1.0 
gradle skip abstract class

**Comment by cbeust** [comment]
Fixed in 1.0.70. Do the following:

```
./kobaltw --update
./kobaltw test
```

You should get this:
