### ISSUE TITLE
Improvement: need additional "starting" state for Kobalt server

### ISSUE THREAD

**Issue by dmitry-zhuravlev** [cbeust/kobalt#418]
Currently it is possible to get several instances of the Kobalt server running:
1) Make sure you have no one server instance running.
2) Open Kobalt `project1` in IDEA.
3) Open Kobalt `project2` in IDEA.
4) Press refresh Kobalt project on `project1`.
5) While `project1` refreshing,  press refresh on `project2`

In the result plugin start additional server instance because it cannot determine that server in "starting" state.
Plugin's `fun isServerRunning(): Boolean` try to execute `ping` on the server instance but obviously fail if server in starting state....

Having several instances running at the same time could lead to unpredictable wrong behavior because the port in `kobaltServer.properties` will be the latest one. Different IDEA instances could connect to not valid Kobalt server and hence get wrong dependencies. E.g. sometimes I got dependencies in `project1` which belongs to `project2` and vise versa. Such crazy things could happen :)

@cbeust thoughts?

**Comment by cbeust** [comment]
The port file gets created pretty much as soon as the server starts, so maybe the plug-in should try to ping it a few times before deciding to launch a new server?

I'm not sure what else we could do about this problem...

**Comment by dmitry-zhuravlev** [comment]
`ping` several times cannot guarantee that server **will** start.  So this will hide the problem but not solve it in general. Also `ping` several times will increase overall refresh time. 
Maybe Kobalt server can mark its state in `kobaltServer.properties` like `starting` and `started` and remove this when it shut down via `quit` command?

**Comment by cbeust** [comment]
But how long does it take for the server to start? Isn't it a minuscule window?

**Comment by dmitry-zhuravlev** [comment]
Not so minuscule... Several times I got some "magic" and wondering why my project got dependencies from other project :) It is because I usually have multiple project opened at the same time and press "refresh" very often at the same time....

**Comment by cbeust** [comment]
So that I don't understand how it could happen. Once a connection is established with one server, you're going to be talking to that server, even if another one is started in the meantime.

If you received dependencies from another project, I think the bug is more in the global state of that server you're connected to instead of the fact there might be multiple servers running.

Agree/disagree?

Back to the startup thing: the server starts pretty fast on my machines (< 2 seconds) so a simple ping followed by another ping two seconds later should tell you for sure if there's a server starting and you contacted it at the wrong time. But really, the odds of this happening are really minuscule, aren't they?

**Comment by dmitry-zhuravlev** [comment]
Partly agree.... Probably there is also some static things like `Kobalt.buildClasspath` which cause such wrong behavior.

Startup time on my different machines varied.  But on the most slow one it is ~4-5s and it is enought to press refresh at the same time.

**Comment by cbeust** [comment]
That's easy to fix on your side: once the user presses the Sync button, ignore additional presses until you've heard back from the sync.

I'm more concerned about getting rid of all the static state on the server that can leak from one connection to the next. Have you seen this happen again since your latest fix?

**Comment by dmitry-zhuravlev** [comment]
> ignore additional presses

It is already ignored inside one IDEA intance. But you cannot check that user press refresh in different instances of IDEA.

Regarding possible "static state leak"- yes I observe this on the latest Kobalt version and it happens from time to time. The problem can be reproduced by steps mentioned in first comment. Just take 2 big Kobalt projects (like Kobalt itself) and execute refresh simultaneously on both.

**Comment by cbeust** [comment]
Presses in a different instances of IDEA (or even just in a different project) are safe. At best, the same server is reused. At worst, a new server is launched. It's unfortunate to have two servers running but it will never produce a wrong result for the user.

I suggest we (well, mostly I :-)) focus on getting rid of global state when in server mode.

**Comment by dmitry-zhuravlev** [comment]
> It's unfortunate to have two servers running but it will never produce a wrong result for the user.

Ok but still have several abandoned server instances alive it is not good. One time I have ~8 instances running and only the latest one was in use. So maybe if the server doesn't accept requests for a long time it can be shutdown automatically? Another approach is to create some special "locked file" during server start. Plugin can try to accure the lock on the given file and if fail that will mean that server was already starting/started. It is more sofisticated approach and could be more tricky to determine wrong behavior like "server locked file but fails to start".

>I suggest we (well, mostly I :-)) focus on getting rid of global state when in server mode.

👍 Fully agree here. Also it could be extracted to the different issue.

**Comment by cbeust** [comment]
Yes, I actually started working on this yesterday because I came to the
same conclusion: a server will automatically shut down if it hasn't
received anything within a period of time.


-- 
Cédric

**Comment by cbeust** [comment]
Done in 1.0.75.

The default time to live is ten minutes: if the server doesn't receive any call (`ping` or `getDependencyGraph`) during that time, it will automatically quit.

Let me know how it works for you and if you'd like it to be configurable at launch time.
