### ISSUE TITLE
vcsTag not passed to Bintray

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#419]
Defined in [Build.kt](https://github.com/ethauvin/kobalt-exec/blob/master/kobalt/src/Build.kt#L62) but not in [kobalt-exec/0.6.4](https://bintray.com/ethauvin/maven/kobalt-exec/0.6.4)

**Comment by cbeust** [comment]
Looking at the [bintray API doc](https://bintray.com/docs/api/), the tag is called `vcs_tag`:

```
{
  "desc": "This package...",
  "github_release_notes_file": "RELEASE_1.2.3.txt",
  "github_use_tag_release_notes": true,
  "vcs_tag": "1.1.5",
  "released": "ISO8601 (yyyy-MM-dd'T'HH:mm:ss.SSSZ)"
}
```

Kobalt captures it as

```
        class UpdateVersion(val desc: String?, val vcsTag: String?)
```

Maybe `vcsTag` is being marshalled to JSON as `vcsTag` and not `vcs_tag`?

**Comment by ethauvin** [comment]
Want me to look at that, and that is still on your radar?

**Comment by cbeust** [comment]
Go ahead.

Somebody recently complained I didn't tag the latest JCommander release so I'm interested in getting this fixed too :-)
