### ISSUE TITLE
KobaltLogger oddities

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#420]
`warn(message, e)`

If one goes through the effort of specified both a `message` and `exception`, shouldn't that `message` be displayed to the user? The exception message will be displayed in the stacktrace.

 I guess that applies to `error` too.

Additionally, have you considered using `yellow` instead of `red` for warnings?

**Comment by cbeust** [comment]
You're welcome to fix `KobaltLogger`, I'm not very happy with its current shape.

Include screenshots with your changes once you send the PR so I can get an idea of what it looks like.

Also, the latest Maven is using some colors, might be worth checking it out and see if there's anything we could reuse.

**Comment by cbeust** [comment]
FYI, I initially used yellow for warnings but it produced poor results in some of the consoles I use, which have a yellowish background:

![image](https://cloud.githubusercontent.com/assets/92322/25241934/9ed28562-25ac-11e7-8b0e-a581882fce2e.png)

The problem with colors is getting them to work with both consoles with a dark and a light background, you'll have to test your experiments with both.

**Comment by ethauvin** [comment]
I'll look into Maven, but what about using _bold_ for warnings, that works regardless of the console colors?

**Comment by cbeust** [comment]
Bold sounds fine.

**Comment by ethauvin** [comment]
Bold is a bust. Bold is basically a highlight, and the messages are already highlighted.

I'll look at Maven, but from what I've read, the best solution is to also control the background color, which is quite doable.

**Comment by cbeust** [comment]
Sure, you can specify the background and the foreground, the hard part is to make it look good with the color scheme of the console...

**Comment by ethauvin** [comment]
We could use `red on black` for errors, and `yellow on black` for warnings. It'll look like a highlight on non-black consoles.

**Comment by ethauvin** [comment]
Maven uses: https://github.com/fusesource/jansi for color, and it doesn't address any of the issues above.
