### ISSUE TITLE
localMaven broken

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#421]
Easiest way to reproduce is by running the example of https://github.com/ethauvin/kobalt-maven-local

```
git clone https://github.com/ethauvin/kobalt-maven-local.git
cd kobalt-maven-local/example
./kobaltw run --log 2
```
It'll print `localMaven()`:

```
>>> LOCAL MAVEN REPO: path/to/example/m2/repository
```
but does not show in the repos:

```
Final list of repos:
  http://repo1.maven.org/maven2/
  file:/C:/Users/erik/.kobalt/localMavenRepo/
  https://jcenter.bintray.com/
```

**Comment by cbeust** [comment]
Since this directory can be modified in your `settings.xml` and I think it's good enough, closing this.

Yell if you disagree :)
