### ISSUE TITLE
Marking dependency as apt() not calling annotation processor

### ISSUE THREAD

**Issue by Redrield** [cbeust/kobalt#427]
When trying to use my custom made annotation processor that generates program metadata and puts it in a file at the root of the folder, Kobalt fails to call the annotation processor. Code for the processor is at https://github.com/Redrield/PluginYamlGenerator.

Code it's failing in: https://github.com/Redrield/KotlinGUIFramework

Kobalt version: 1.0.72

**Comment by cbeust** [comment]
The second one is 404. Can you update this issue and reopen if it's still a problem?
