### ISSUE TITLE
fatJar are not always fat

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#429]
Using the following:
```
    assemble {
        jar {
            fatJar = true
        }

        mavenJars {}
    }
```
The jar created is definitely not fat, using `publishToMavenLocal`.

~~I would have said this would be a major issue with plugins, but as far as I can tell Kobalt now downloads plugins dependencies. Don't think there is a need to make plugins fat anymore.~~

Nevertheless, the issue remains.

**Comment by ethauvin** [comment]
Okay, the problem can be solved by doing:

```
    assemble {
        jar {
            fatJar = true
        }

        mavenJars {
            fatJar = true
        }
    }
```

It didn't used to be that way.

**Comment by cbeust** [comment]
This seems to be working as intended then.
