### ISSUE TITLE
application plugin changes where kobalt assembles jar

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#434]
is it intentional that when no `application` directive is used, kobalt places assembled jars in `kobaltBuild/libs` and when `application` **is** used, assembled fatJars land in `libs`?

**Comment by cbeust** [comment]
Nope, definitely a bug, and should be easy to fix.

**Comment by cbeust** [comment]
I can't reproduce this. I added an empty `application{}` and all the jar files are in `kobaltBuild/libs`.

Can you link to a project that reproduces this?

Thanks.
