### ISSUE TITLE
The WAR filename contains `null` if version information is missing

### ISSUE THREAD

**Issue by McPringle** [cbeust/kobalt#456]
Example buildfile:

```kotlin
val foobar = project {
    name = "foobar"
    group = "test.foobar"
    artifactId = name

    dependencies {
        compile("org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.50")
    }

    assemble {
        war {}
    }
}
```

Name of the file which was created: `foobar-null.war`

If a version number is optional, it should only be added to the filename if it was specified. I would never expect `null` in a filename. If the version number is required, then the build should fail with a useful error message.

In my opinion, the version number should be optional and not be part of the artifact filename if it was not specified. I would like to learn more about Kobalt and try to solve this problem. Let's see what you will say to my PR… ;-)

**Comment by cbeust** [comment]
Will happily accept a PR to fix this :)

**Comment by McPringle** [comment]
Works with Kobalt 1.0.91!
