### ISSUE TITLE
kobaltw contains carriage return + newline

### ISSUE THREAD

**Issue by medovina** [cbeust/kobalt#467]
I'm running Ubuntu 17.10.

I wanted to try out Kobalt, so I just downloaded and extracted the zip file as instructed at

http://beust.com/kobalt/getting-started/index.html

I added the directory containing kobaltw to my PATH, then went to an empty directory and typed

```
$ kobaltw --init kotlin
```

And I got this error:

```
/usr/bin/env: ‘sh\r’: No such file or directory
```

The problem is that kobaltw contains a \r\n at the end of the first line ("#!/usr/bin/env sh").  Ubuntu and many other Unix-like systems don't like this.

**Comment by ethauvin** [comment]
It's been an ongoing issue. There are no carriage returns in the source tree file, but depending on which platform @cbeust assembles the release on, carriage returns are inserted during the zipping process.

**Comment by cbeust** [comment]
Mmmh I thought we had a test for this, guess not, sorry for the trouble. You can edit `kobaltw` yourself for now, but feel free to send a PR and I'll cut a new release.

**Comment by cbeust** [comment]
FIxed in latest.
