### ISSUE TITLE
kobalt not setting me up to use ktor in IntelliJ IDEA

### ISSUE THREAD

**Issue by whiteknight-** [cbeust/kobalt#482]
I can't get IntelliJ IDEA to recognize ktor after importing the project through the kobalt plugin. I already did the init, assemble, and compile steps before trying to import the project in IDEA. No folders appear in the project window. Am I missing something? I've used kobalt before on another project and it worked beautifully, just not here. Here's my build.kt file:

import com.beust.kobalt.*
import com.beust.kobalt.plugin.packaging.*
import com.beust.kobalt.plugin.application.*
import com.beust.kobalt.plugin.kotlin.*

val bs = buildScript {
    repos("https://dl.bintray.com/kotlin/ktor/")
}

val p = project {
    name = "SimpleWebAPI"
    group = "com.example"
    artifactId = name
    version = "0.1"

    dependencies {
        compile("io.ktor:ktor-server-core:0.9.3")
        compile("io.ktor:ktor-server-netty:0.9.3")
        compile("org.jetbrains.kotlin:kotlin-runtime:1.2.51")
        compile("org.jetbrains.kotlin:kotlin-stdlib:1.2.51")
    }

    dependenciesTest {
        compile("io.kotlintest:kotlintest:2.0.7")
    }

    assemble {
        jar {
        }
    }

    application {
        mainClass = "com.example.MainKt"
    }
}

**Comment by cbeust** [comment]
I think you should file this at https://github.com/cbeust/kobalt-intellij-plugin

**Comment by whiteknight-** [comment]
Thank you for the link, sir. I will post my issue there.
