### ISSUE TITLE
Publishing "multi-project" project to Bintray?

### ISSUE THREAD

**Issue by johanhaleby** [cbeust/kobalt#486]
What's recommended approach to publish a Kobalt project containg multiple projects? I have a [library](https://github.com/johanhaleby/kystrix) that consists of a "core" project and a "spring" project (which depends on "core"). Currently both projects are configured with:

```
bintray {
        publish = true
        sign = true
    }
```

but I suspect that this won't work since, if I understand it correctly, bintray opens a single staging repository for both artifacts and you can't publish this repository twice? Or have I misunderstood something here?

**Comment by cbeust** [comment]
Hi @johanhaleby,

Kobalt itself is made of three different projects, can you just copy what it does?

And if you want to include transitive dependencies, all you need is `fatJar = true`.

**Comment by johanhaleby** [comment]
@cbeust Thanks! Hadn't looked at build file for kobat itself, seem to be a great resource. I'll give it a try :)
