### ISSUE TITLE
Use with CI

### ISSUE THREAD

**Issue by davidsowerby** [cbeust/kobalt#491]
First, thanks for this project, it looks like an interesting and much simpler alternative to Gradle.

One thing I cannot find in your documentation - how would I go about handling properties (specifically access keys) while running a Kobalt build in a CI environment?

The Gradle equivalent is to prefix environment variables with **ORG_GRADLE_PROJECT_**    - Gradle picks that up and converts it to a project property.  

**ORG_GRADLE_PROJECT_ACCESS_KEY** then becomes a project property **ACCESS_KEY**

Is there anything similar in Kobalt?

**Comment by cbeust** [comment]
You could simply define these environment variables in your CI and then access them the regular, Java way, in your `Build.kt`?

**Comment by davidsowerby** [comment]
That was such an obvious answer I almost wish I hadn't asked the question :-) 

Many thanks for the quick response.
