### ISSUE TITLE
Kobalt compiler using Kotlin 1.2.70, Ktor needs at least Kotlin 1.3

### ISSUE THREAD

**Issue by whiteknight-** [cbeust/kobalt#504]
[screenshot of cli](https://imgur.com/a/Cyne10K)

Hi cbeust, I'm trying to generate a Fat JAR for Ktor. It looks like the internal Kotlin compiler in Kobalt is using an older version of Kotlin (1.2.70). If you look in the screenshot, it looks like a Route is only available in Kotlin 1.3 for use in Ktor. I hope you can fix.

**Comment by cbeust** [comment]
Fixed in 1.0.125. Your next `./kobaltw assemble` should update to 1.0.125 which updates to Kotlin 1.3.41.
