### ISSUE TITLE
Add support for Android Library (aar) projects

### ISSUE THREAD

**Issue by fboldog** [cbeust/kobalt#53]
Android Library project shuold generate output as .aar.
Structure of aar is well defined:  https://drive.google.com/a/ustream.tv/folderview?id=0B5cgMScVdti7LUllUGVGWmQ2R0E&usp=sharing

**Comment by pawegio** [comment]
+1

**Comment by asarazan** [comment]
Also +1! 

:wave: @pawegio

**Comment by cbeust** [comment]
Example project provided by @asarazan :  https://github.com/levelmoney/velodrome

**Comment by cbeust** [comment]
@fboldog I can't see to access that Google doc.

**Comment by fboldog** [comment]
Oops. Bad link (Company internal...)
This is the correct link:
http://tools.android.com/tech-docs/new-build-system/aar-format

**Comment by cbeust** [comment]
Yes, I got it.

I think this should be pretty straightforward and mostly already there: I noticed a few boolean flags in the com.android.builder API's that define whether the package being built is an apk or a library. Simply turning these on might be enough for kobalt to produce aar's.

Will take a look.
