### ISSUE TITLE
Handle aapt error returns

### ISSUE THREAD

**Issue by fboldog** [cbeust/kobalt#57]
For example:
android-project/kobaltBuild/intermediates/manifests/full/AndroidManifest.xml:7: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/ic_launcher').

To reproduce: remove all launcher drawable from the project and start the build and keep reference in AndroidManifest.xml

**Comment by cbeust** [comment]
Yes, aapt exits with 0 even in case of errors, but I have a workaround

**Comment by fboldog** [comment]
:tada:

**Comment by cbeust** [comment]
Should be fixed in 0.303.
