### ISSUE TITLE
support repositories that need authentication

### ISSUE THREAD

**Issue by christophsturm** [cbeust/kobalt#60]
in our company we have our own nexus server, and we use password authentication for it.

all of our build files contain this fragment:
<pre>
repositories {
    mavenCentral()
    maven {
        credentials {
            username 'ci'
            password 'password'
        }
        url "http://nexus001.internal:8081/nexus/content/repositories/snapshots"
    }
}
</pre>

it would be great if kobalt could also support this. maybe without all the verbosity
<pre>
val repos = repos("ci:password@http://nexus001.internal:8081/nexus/content/repositories/snapshots")
</pre>

**Comment by cbeust** [comment]
I can cut down on the verbosity but I think the credentials should not be in the build file, so instead, they should refer to key/value in `local.properties`. What do you think of:

    val r = repos("http://something", { keyUser: "repoUser", keyPassword: "repoPassword" })

and then in your `local.properties`:

    repoUser=cbeust
    repoPassword=xxx

?

**Comment by cbeust** [comment]
Also, do you know of an easy way to test authenticated repos?

**Comment by christophsturm** [comment]
I think its a good idea to put the credentials into a properties file. but one problem with that approach that I have seen is that people use different keys for the passwords, so my properties file ended up like this:
<pre>
nexusUser=user
nexusPassword=password
CompanyNameNexusUser=user
CompanyNameNexusPassword=password
FunnyProjectNameNexusUser=user
FunnyProjectNameNexusPassword=password
</pre>
.. all with the same user and password.

so maybe there should be a default value for the key? kobaltRepoUser, kobaltRepoPassword? Just an idea, maybe it's not really so important. 

also maybe user:password@url should still be supported because some auth credentials are just so weak that you can just put it into the source,  but for some reason you are forced to use auth. 

and for testing http repos i would probably use http://wiremock.org

**Comment by christophsturm** [comment]
what about searching projectName.repoUser/Password first and falling back to just repoUser/password
(and allowing to override the key in case one project has more than one private repo, which is probably the minority)?

**Comment by cbeust** [comment]
0.314 contains a first pass at this. Here is the current syntax:

    val r = repos("http://dl.bintray.com/kotlin/kotlinx.dom")
    val r2 = repos(
        authRepo("http://localhost:8081/artifactory/ext-release-local", {
            keyUsername = "_admin"
            keyPassword = "password"
        }))

Note:

1. Need to call `repos()` twice, because they're both function with `varargs` and obviously, you can't mix the types. Happy to hear about better suggestions here.
2. Note that even though I called them `keyUsername` and `keyPassword`, right now, these variables contain the actual username and passwords. Eventually, they will be key into your `local.properties`, as I hinted above.

Please try this on your repo and let me know how it works for you. This change impacted a lot of things so it might not quite work yet (but it works on my local artifactory instance).

**Comment by christophsturm** [comment]
is the old repos() syntax without parameters no longer supported?

**Comment by cbeust** [comment]
No, both syntaxes work.

**Comment by christophsturm** [comment]
i got a compile error with repos=repos()
<pre>
/private/var/folders/99/084s2g6s4pbgwr4_46ysxms80000gn/T/kobalt2727741695081263897.kt:3:7: error: overload resolution ambiguity: 
@com.beust.kobalt.api.annotation.Directive public fun repos(vararg repos: com.beust.kobalt.HostInfo): kotlin.Unit defined in com.beust.kobalt
@com.beust.kobalt.api.annotation.Directive public fun repos(vararg repos: kotlin.String): kotlin.Unit defined in com.beust.kobalt
val r=repos()
      ^
/private/var/folders/99/084s2g6s4pbgwr4_46ysxms80000gn/T/kobalt6717919338312961304.kt:5:7: error: overload resolution ambiguity: 
@com.beust.kobalt.api.annotation.Directive public fun repos(vararg repos: com.beust.kobalt.HostInfo): kotlin.Unit defined in com.beust.kobalt
@com.beust.kobalt.api.annotation.Directive public fun repos(vararg repos: kotlin.String): kotlin.Unit defined in com.beust.kobalt
val r=repos()
</pre>

**Comment by cbeust** [comment]
Are you calling `repos()` with no parameters? Remove it, then, otherwise it is indeed ambiguous.

**Comment by cbeust** [comment]
Current plan is to move the authentication to `local.properties`:

    authRepo.example.com.user=...
    authRepo.example.com.password=...

**Comment by cbeust** [comment]
0.315 implements what we just discussed:  http://beust.com/kobalt/documentation/index.html#maven-repos-authenticated

@christophsturm  Please confirm it's working for you.

**Comment by christophsturm** [comment]
thanks! I can't confirm that it works but I'm sure that it does. our private repo is now in a vpn and has no auth anymore. (which is much better anyways)
