### ISSUE TITLE
transitive dependencies for jetty-client are not resolved.

### ISSUE THREAD

**Issue by christophsturm** [cbeust/kobalt#61]
org.eclipse.jetty:jetty-client:9.2.8.v20150217 has some transitive dependencies that are not resolved by kobalt.

<pre>
~/Projects/collmedia/pint-adapter-buzz% ./kobaltw --resolve org.eclipse.jetty:jetty-client:9.2.8.v20150217
[Wrapper] /Users/christoph/Projects/collmedia/pint-adapter-buzz/./kobaltw already exists, not overwriting it
[Wrapper] /Users/christoph/Projects/collmedia/pint-adapter-buzz/./kobalt/wrapper/kobalt-wrapper.jar already exists, not overwriting it
            _  __          _               _   _   
           | |/ /   ___   | |__     __ _  | | | |_ 
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_ 
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.314

info: PERF: INIT: Compiler initialized in 602 ms
info: PERF: ANALYZE: 1 files (78 lines) in 953 ms
info: PERF: GENERATE: 1 files (78 lines) in 158 ms
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                          org.eclipse.jetty:jetty-client:9.2.8.v20150217                                 ║
║           http://repo1.maven.org/maven2/org/eclipse/jetty/jetty-client/9.2.8.v20150217/jetty-client-9.2.8.v20150217.jar ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

</pre>
for comparision this is what gradle outputs:
<pre>
+--- org.eclipse.jetty:jetty-client:9.2.8.v20150217
|    +--- org.eclipse.jetty:jetty-http:9.2.8.v20150217
|    |    \--- org.eclipse.jetty:jetty-util:9.2.8.v20150217
|    \--- org.eclipse.jetty:jetty-io:9.2.8.v20150217
|         \--- org.eclipse.jetty:jetty-util:9.2.8.v20150217
</pre>

**Comment by cbeust** [comment]
Interesting, will take a look shortly. Thanks!

-- 
Cédric

**Comment by cbeust** [comment]
Kobalt currently doesn't handle variables, and the `.pom` contains:

```
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-http</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-io</artifactId>
      <version>${project.version}</version>
    </dependency>
```

I'm guessing `${project.version}` comes from:

```
  <parent>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-project</artifactId>
    <version>9.2.8.v20150217</version>
  </parent>
```

? (will have to look up that spec)

@evanchooly, any thoughts?

**Comment by christophsturm** [comment]
maybe it should emit an error when it fails to parse the pom?

**Comment by cbeust** [comment]
Definitely. I'll take a look but let me know if you'd like to send a PR :)

**Comment by christophsturm** [comment]
sure, as soon as i have my dev enviroment set up i will look into contributing. for now I'm just creating issues while i move build files to kobalt.
