### ISSUE TITLE
run tasks in the correct order

### ISSUE THREAD

**Issue by christophsturm** [cbeust/kobalt#62]
./kobaltw clean test assemble runs assemble before test. I think it should run in the order specified on the commandline.

also how do i specify that assemble should always run test? I'm one of those people who think that anytime something is built the test suite should also run :)

**Comment by cbeust** [comment]
The command line doesn't specify the order, just the tasks to run. The tasks know better in which order they should be running.

I guess I could make `test` run before `assemble` and just use the `classes` directory on the classpath instead of the jar file.
