### ISSUE TITLE
very verbose warning about missing properties file

### ISSUE THREAD

**Issue by christophsturm** [cbeust/kobalt#64]
<pre>
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
  Compiling 11 files
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
***** WARNING Couldn't find a local.properties file
</pre>

**Comment by cbeust** [comment]
Yes, I noticed this too, will fix.

-- 
Cédric

**Comment by cbeust** [comment]
Fixed by https://github.com/cbeust/kobalt/commit/4354d37ecf6c5c8e26603513d16a00c06cd92d76
