### ISSUE TITLE
Allow files to be included into the build definition that might be generated

### ISSUE THREAD

**Issue by apatrida** [cbeust/kobalt#7]
Make sure there is an easy way to include files that are generated into a build (i.e. version management writing a version file, or `brikk` writing a dependency definition)

This is not for a "generated sources" directory for the contents of what is being built, but rather that the build scripts itself might have some included from outside generators.

**Comment by cbeust** [comment]
What do you mean by "include files"? In a jar file?

**Comment by apatrida** [comment]
an additional source file to go along with `build.kt` included easily into the definition of the build.  I think for the case of kobalt, the plugin model is so light-weight that this makes less sense.  With Gradle it would be "apply from: 'filename'" ...  For Kobalt would be another source file for the build in the compile path of the build scripts.

**Comment by cbeust** [comment]
Yes, these files go into `kobalt/src`. You can already put `Build.kt` there but I don't support extra files just yet, but it's definitely planned. [See TODO](https://github.com/cbeust/kobalt/blob/master/TODO#L12).
