### ISSUE TITLE
--checkVersions should not show SNAPSHOT releases

### ISSUE THREAD

**Issue by christophsturm** [cbeust/kobalt#75]
<pre>
New versions found:
        com.fasterxml.jackson.core:jackson-core:2.7.0-rc2
        org.apache.commons:commons-lang3:3.5-SNAPSHOT
        com.fasterxml.jackson.core:jackson-databind:2.7.0-rc2
        com.fasterxml.jackson.module:jackson-module-parameter-names:2.7.0-rc2
        junit:junit:5.0-SNAPSHOT
        com.fasterxml.jackson.core:jackson-annotations:2.7.0-rc2
BUILD SUCCESSFUL (11 seconds)
</pre>
also it would be nice if rc releases could be configured in the build file. (Usually I don't want to use rc releases in production, but its ok for a project that is still in early development)

**Comment by cbeust** [comment]
Good point about `SNAPSHOT` releases.
