### ISSUE TITLE
Dependencies can be local files

### ISSUE THREAD

**Issue by apatrida** [cbeust/kobalt#8]
Allow dependencies to be local files, not only maven or remote.  This comes in two flavours:

A list of JAR's on filesystem
A list of class dirs on filesystem (allows plugging projects together that are compiled at same time)
A maven repo that is a local disk (local maven repo, user maven repo on disk, ...)

These all should support all scopes of dependencies (compile, provided, runtime, test compile, test provided, test runtime)

**Comment by cbeust** [comment]
Already supported with `file()`:

https://github.com/cbeust/kobalt/blob/master/kobalt/src/Build.kt#L15
