### ISSUE TITLE
Make "internal" scope visible from unit tests

### ISSUE THREAD

**Issue by asarazan** [cbeust/kobalt#85]
Filed against version 0.368

**Comment by asarazan** [comment]
Additional context: Files in the `test` source set do not have proper access to `internal` val/vars in the `main` source set.

Works fine from the IntelliJ runner, but fails on the `kobaltw` runner

**Comment by cbeust** [comment]
Appears to be a Kotlin bug, filed https://youtrack.jetbrains.com/issue/KT-10549
