### ISSUE TITLE
Support all common scopes of dependencies

### ISSUE THREAD

**Issue by apatrida** [cbeust/kobalt#9]
Support all the common scopes of dependencies:

compile, provided, runtime, test compile, test provided, test runtime

**Comment by cbeust** [comment]
`compile`, `compileTest`, `provided` are already supported. I forgot to add `providedTest` but it's a trivial fix (see `Project.kt`).

Not sure how `runtime` different from `provided`(?).

**Comment by apatrida** [comment]
Runtime are things you don't compile against but need for runtime,or example slf4j is compile but logback is runtime.   Provided means someone else brings it along.  Like a Web container or user of your library.   They are not the same. 

If I'm writing an app I might include mysql driver as runtime.   I don't directly talk to it, jdbc finds it. I talk to the API not the library.  But I still need it to run and want to ship it. 

One jar would include runtime but not provided.  An app or library could have this scope. 

An app distribution would include runtime, but not provided.  A library distribution the same.   

It's in every build system and Intellij and eclipse and is used.  And expected.
