### ISSUE TITLE
Should allow to upload unsigned jars to jcenter

### ISSUE THREAD

**Issue by bmsantos** [cbeust/kobalt#92]
```gherkin
Feature: Upload jar
  Scenario: Should upload unsigned jar
    Given an assembled jar
    And the uploadJcenter task is flagged to not sign the jar
    When the uploadJcenter task is executed
    Then the jar will not be signed
    And the jar will be uploaded to jCenter Bintray
```

**Comment by cbeust** [comment]
Fixed in https://github.com/cbeust/kobalt/commit/4ab161cf1d47b50e94f0be18e963e11a0077dfe2

**Comment by bmsantos** [comment]
When you commit you can refer the commit to the issue by including #<issue number> (#92 in this case) in the commit message. That will automatically show the commit in the issue thread.

**Comment by cbeust** [comment]
Yeah I know but I always forget :)

-- 
Cédric
