### ISSUE TITLE
JUnit tests don't work in Kobalt versions above 0.365

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#97]
When I run the test task with anything above 0.365, it's as if the JUnit tests simply never run.  In 0.366 and 0.367 there's not even a message indicating that anything failed.  In 0.390 i get a message saying the build failed.

**Comment by pabl0rg** [comment]
I thought it might work with TestNG, so I switched to TestNG and had the same problem.  Here are excepts from ./kobaltw --log 3 backend-java:test

0.365
"""
===============================================
Command line suite
Total tests run: 91, Failures: 0, Skips: 0
===============================================

All tests passed
  <== Received task result {TaskResult value:{PluginTask id:backend-java:test}, success:true}
    freeNodes: []
    freeNodes: []
"""

0.390:
"""
───── backend-java:test
backend-java: Running tests
Skipping variable version Dependency(groupId=org.fusesource.hawtbuf, artifactId=hawtbuf, packaging=null, version=${hawtbuf-version}, optional=false, scope=null)
Skipping variable groupId Dependency(groupId=${project.groupId}, artifactId=activemq-jms-pool, packaging=null, version=, optional=false, scope=null)
Skipping variable groupId Dependency(groupId=${project.groupId}, artifactId=activemq-client, packaging=null, version=, optional=false, scope=null)
Skipping variable version Dependency(groupId=com.squareup.retrofit, artifactId=retrofit, packaging=null, version=${project.version}, optional=false, scope=null)
  <== Received task result {TaskResult value:{PluginTask id:backend-java:test}, success:false}
Node in error: {PluginTask id:backend-java:test}
    freeNodes: []
    freeNodes: []
"""

**Comment by cbeust** [comment]
At least the Kobalt tests are running:

```
===============================================
Kobalt
Total tests run: 46, Failures: 3, Skips: 0
===============================================

Test failures
BUILD FAILED: 1
```

Is your project on github? Can I build it myself?

**Comment by pabl0rg** [comment]
I think it has to do with mixed projects or the way i've configured the
build file for them.

I made an example on github:
https://github.com/pabl0rg/kobalt-mixed-example.git

If you run kobaltw test as is (v 0.365), the tests run OK

If you edit kobalt/wrapper/kobalt-wrapper.properties to 0.390 they don't
and the build fails.

Thanks

**Comment by cbeust** [comment]
Thanks for the project! It's fixed in the latest version.
